package main

var (
	// ARG (compiler/linker token) constants, interned once. Generated by `ay refac consts`.
	argC                        = internArg("c++")
	argDMusl                    = internArg("-D_musl_")
	argDashG                    = internArg("-g")
	argDuseCurrentUdfAbiVersion = internArg("-DUSE_CURRENT_UDF_ABI_VERSION")
	argDusePython3              = internArg("-DUSE_PYTHON3")
	argFPIC                     = internArg("-fPIC")
	argFatalWarnings            = internArg("--fatal_warnings")
	argGzZstd                   = internArg("-gz=zstd")
	argNDEBUG                   = internArg("-DNDEBUG")
	argNoOutlineAtomics         = internArg("-mno-outline-atomics")
	argNoShadow                 = internArg("-Wno-shadow")
	argUNDEBUG                  = internArg("-UNDEBUG")
	argWnoDeprecatedCopy        = internArg("-Wno-deprecated-copy")
	argWnoImplicitFallthrough   = internArg("-Wno-implicit-fallthrough")
	argWnoUnusedButSetVariable  = internArg("-Wno-unused-but-set-variable")
	argWnoUnusedVariable        = internArg("-Wno-unused-variable")
	argX                        = internArg("-x")
	baseUnitCxxNostdinc         = internArg("-nostdinc++")
	cxxStandardFlag             = internArg("-std=c++20")
)
