// Code generated by dev/gen_densemap.py; DO NOT EDIT.

package main

// denseRow3 holds one 1-based slot per value column of a DenseMap3 row;
// a slot of 0 means that column is unset for the key.
type denseRow3 struct {
	i1, i2, i3 uint32
}

// DenseMap3 maps a dense integer key K to 3 independent value columns,
// each with its own presence and dense storage, sharing a single K-sized idx
// array. idx maps a present key to a 1-based row slot in rows; each row holds
// 3 1-based slots, one per column, into that column's valsM table
// (a row slot of 0 = column unset for the key). See dev/gen_densemap.py for
// the rationale versus N separate DenseMaps or a DenseMap of a struct.
type DenseMap3[K ~uint32, V1, V2, V3 any] struct {
	idx   Vec[uint32]
	rows  Vec[denseRow3]
	vals1 Vec[V1]
	vals2 Vec[V2]
	vals3 Vec[V3]
}

// rowSlot returns the 1-based row slot for k, or 0 when k has no row yet.
func (m *DenseMap3[K, V1, V2, V3]) rowSlot(k K) uint32 {
	if int(k) < m.idx.len() {
		return m.idx.s[k]
	}

	return 0
}

// ensureRow returns k's row slot, allocating an empty row on first touch.
func (m *DenseMap3[K, V1, V2, V3]) ensureRow(k K) uint32 {
	if int(k) < m.idx.len() {
		if slot := m.idx.s[k]; slot != 0 {
			return slot
		}
	}

	if m.rows.len() == 0 {
		m.rows.pushBack(denseRow3{}) // reserve slot 0 as the absent sentinel
	}

	m.idx.ensureLen(int(k) + 1)
	m.rows.pushBack(denseRow3{})
	slot := uint32(m.rows.len() - 1)
	m.idx.s[k] = slot

	return slot
}

// get1 returns column 1's value for k and whether that column is present.
func (m *DenseMap3[K, V1, V2, V3]) get1(k K) (V1, bool) {
	if slot := m.rowSlot(k); slot != 0 {
		if vi := m.rows.s[slot].i1; vi != 0 {
			return m.vals1.s[vi], true
		}
	}

	var zero V1

	return zero, false
}

// put1 sets column 1's value for k.
func (m *DenseMap3[K, V1, V2, V3]) put1(k K, v V1) {
	slot := m.ensureRow(k)

	if vi := m.rows.s[slot].i1; vi != 0 {
		m.vals1.s[vi] = v

		return
	}

	if m.vals1.len() == 0 {
		m.vals1.pushBack(*new(V1)) // reserve slot 0 as the absent sentinel
	}

	m.vals1.pushBack(v)
	m.rows.s[slot].i1 = uint32(m.vals1.len() - 1)
}

// get2 returns column 2's value for k and whether that column is present.
func (m *DenseMap3[K, V1, V2, V3]) get2(k K) (V2, bool) {
	if slot := m.rowSlot(k); slot != 0 {
		if vi := m.rows.s[slot].i2; vi != 0 {
			return m.vals2.s[vi], true
		}
	}

	var zero V2

	return zero, false
}

// put2 sets column 2's value for k.
func (m *DenseMap3[K, V1, V2, V3]) put2(k K, v V2) {
	slot := m.ensureRow(k)

	if vi := m.rows.s[slot].i2; vi != 0 {
		m.vals2.s[vi] = v

		return
	}

	if m.vals2.len() == 0 {
		m.vals2.pushBack(*new(V2)) // reserve slot 0 as the absent sentinel
	}

	m.vals2.pushBack(v)
	m.rows.s[slot].i2 = uint32(m.vals2.len() - 1)
}

// get3 returns column 3's value for k and whether that column is present.
func (m *DenseMap3[K, V1, V2, V3]) get3(k K) (V3, bool) {
	if slot := m.rowSlot(k); slot != 0 {
		if vi := m.rows.s[slot].i3; vi != 0 {
			return m.vals3.s[vi], true
		}
	}

	var zero V3

	return zero, false
}

// put3 sets column 3's value for k.
func (m *DenseMap3[K, V1, V2, V3]) put3(k K, v V3) {
	slot := m.ensureRow(k)

	if vi := m.rows.s[slot].i3; vi != 0 {
		m.vals3.s[vi] = v

		return
	}

	if m.vals3.len() == 0 {
		m.vals3.pushBack(*new(V3)) // reserve slot 0 as the absent sentinel
	}

	m.vals3.pushBack(v)
	m.rows.s[slot].i3 = uint32(m.vals3.len() - 1)
}

// len reports the number of distinct keys stored (a key counts once any of
// its columns has been set).
func (m *DenseMap3[K, V1, V2, V3]) len() int {
	if m.rows.len() == 0 {
		return 0
	}

	return m.rows.len() - 1
}
