// Code generated by dev/gen_densemap.py; DO NOT EDIT.

package main

import "testing"

func TestDenseMap4_IndependentColumns(t *testing.T) {
	var m DenseMap4[STR, int, int, int, int]

	// Set exactly one column per key (key 0 exercises the slot-0 sentinel).
	m.Put1(0, 100)
	m.Put2(1, 200)
	m.Put3(2, 300)
	m.Put4(3, 400)

	if m.Len() != 4 {
		t.Fatalf("Len = %d, want 4", m.Len())
	}

	// Each key has only its own column present; all others read absent.
	if got, ok := m.Get1(0); !ok || got != 100 {
		t.Fatalf("Get1(0) = (%d, %v), want (100, true)", got, ok)
	}
	if _, ok := m.Get2(0); ok {
		t.Fatalf("Get2(0) present, want absent")
	}
	if _, ok := m.Get3(0); ok {
		t.Fatalf("Get3(0) present, want absent")
	}
	if _, ok := m.Get4(0); ok {
		t.Fatalf("Get4(0) present, want absent")
	}
	if got, ok := m.Get2(1); !ok || got != 200 {
		t.Fatalf("Get2(1) = (%d, %v), want (200, true)", got, ok)
	}
	if _, ok := m.Get1(1); ok {
		t.Fatalf("Get1(1) present, want absent")
	}
	if _, ok := m.Get3(1); ok {
		t.Fatalf("Get3(1) present, want absent")
	}
	if _, ok := m.Get4(1); ok {
		t.Fatalf("Get4(1) present, want absent")
	}
	if got, ok := m.Get3(2); !ok || got != 300 {
		t.Fatalf("Get3(2) = (%d, %v), want (300, true)", got, ok)
	}
	if _, ok := m.Get1(2); ok {
		t.Fatalf("Get1(2) present, want absent")
	}
	if _, ok := m.Get2(2); ok {
		t.Fatalf("Get2(2) present, want absent")
	}
	if _, ok := m.Get4(2); ok {
		t.Fatalf("Get4(2) present, want absent")
	}
	if got, ok := m.Get4(3); !ok || got != 400 {
		t.Fatalf("Get4(3) = (%d, %v), want (400, true)", got, ok)
	}
	if _, ok := m.Get1(3); ok {
		t.Fatalf("Get1(3) present, want absent")
	}
	if _, ok := m.Get2(3); ok {
		t.Fatalf("Get2(3) present, want absent")
	}
	if _, ok := m.Get3(3); ok {
		t.Fatalf("Get3(3) present, want absent")
	}
}

func TestDenseMap4_AllColumnsOneKey(t *testing.T) {
	var m DenseMap4[STR, int, int, int, int]
	const k = 1000

	m.Put1(k, 1)
	m.Put2(k, 2)
	m.Put3(k, 3)
	m.Put4(k, 4)

	if got, ok := m.Get1(k); !ok || got != 1 {
		t.Fatalf("Get1(k) = (%d, %v), want (1, true)", got, ok)
	}
	if got, ok := m.Get2(k); !ok || got != 2 {
		t.Fatalf("Get2(k) = (%d, %v), want (2, true)", got, ok)
	}
	if got, ok := m.Get3(k); !ok || got != 3 {
		t.Fatalf("Get3(k) = (%d, %v), want (3, true)", got, ok)
	}
	if got, ok := m.Get4(k); !ok || got != 4 {
		t.Fatalf("Get4(k) = (%d, %v), want (4, true)", got, ok)
	}

	if m.Len() != 1 {
		t.Fatalf("Len = %d, want 1", m.Len())
	}
}

func TestDenseMap4_OverwriteAndAbsent(t *testing.T) {
	var m DenseMap4[STR, int, int, int, int]

	if _, ok := m.Get1(0); ok {
		t.Fatal("empty map reported key 0 present")
	}
	if _, ok := m.Get1(1 << 20); ok {
		t.Fatal("empty map reported out-of-range key present")
	}

	m.Put1(7, 1)
	m.Put1(7, 2)
	m.Put1(7, 3)

	if got, _ := m.Get1(7); got != 3 {
		t.Fatalf("Get1(7) = %d, want 3 (last write)", got)
	}
	if m.Len() != 1 {
		t.Fatalf("Len = %d, want 1 (overwrite must not add a key)", m.Len())
	}
}
