// Code generated by dev/gen_densemap.py; DO NOT EDIT.

package main

// denseRow3 holds one 1-based slot per value column of a DenseMap3 row;
// a slot of 0 means that column is unset for the key.
type denseRow3 struct {
	i1, i2, i3 uint32
}

// DenseMap3 maps a dense integer key K to 3 independent value columns,
// each with its own presence and dense storage, sharing a single K-sized idx
// array. idx maps a present key to a 1-based row slot in rows; each row holds
// 3 1-based slots, one per column, into that column's valsM table
// (a row slot of 0 = column unset for the key). See dev/gen_densemap.py for
// the rationale versus N separate DenseMaps or a DenseMap of a struct.
type DenseMap3[K ~uint32, V1, V2, V3 any] struct {
	idx   []uint32
	rows  []denseRow3
	vals1 []V1
	vals2 []V2
	vals3 []V3
}

// rowSlot returns the 1-based row slot for k, or 0 when k has no row yet.
func (m *DenseMap3[K, V1, V2, V3]) rowSlot(k K) uint32 {
	if int(k) < len(m.idx) {
		return m.idx[k]
	}

	return 0
}

// ensureRow returns k's row slot, allocating an empty row on first touch.
func (m *DenseMap3[K, V1, V2, V3]) ensureRow(k K) uint32 {
	if int(k) < len(m.idx) {
		if slot := m.idx[k]; slot != 0 {
			return slot
		}
	}

	if len(m.rows) == 0 {
		m.rows = append(m.rows, denseRow3{}) // reserve slot 0 as the absent sentinel
	}

	m.growIdx(int(k))
	m.rows = append(m.rows, denseRow3{})
	slot := uint32(len(m.rows) - 1)
	m.idx[k] = slot

	return slot
}

func (m *DenseMap3[K, V1, V2, V3]) growIdx(k int) {
	if k < len(m.idx) {
		return
	}

	n := len(m.idx) * 2

	if n <= k {
		n = k + 1
	}

	grown := make([]uint32, n)
	copy(grown, m.idx)
	m.idx = grown
}

// Get1 returns column 1's value for k and whether that column is present.
func (m *DenseMap3[K, V1, V2, V3]) Get1(k K) (V1, bool) {
	if slot := m.rowSlot(k); slot != 0 {
		if vi := m.rows[slot].i1; vi != 0 {
			return m.vals1[vi], true
		}
	}

	var zero V1

	return zero, false
}

// Put1 sets column 1's value for k.
func (m *DenseMap3[K, V1, V2, V3]) Put1(k K, v V1) {
	slot := m.ensureRow(k)

	if vi := m.rows[slot].i1; vi != 0 {
		m.vals1[vi] = v

		return
	}

	if len(m.vals1) == 0 {
		m.vals1 = append(m.vals1, *new(V1)) // reserve slot 0 as the absent sentinel
	}

	m.vals1 = append(m.vals1, v)
	m.rows[slot].i1 = uint32(len(m.vals1) - 1)
}

// Get2 returns column 2's value for k and whether that column is present.
func (m *DenseMap3[K, V1, V2, V3]) Get2(k K) (V2, bool) {
	if slot := m.rowSlot(k); slot != 0 {
		if vi := m.rows[slot].i2; vi != 0 {
			return m.vals2[vi], true
		}
	}

	var zero V2

	return zero, false
}

// Put2 sets column 2's value for k.
func (m *DenseMap3[K, V1, V2, V3]) Put2(k K, v V2) {
	slot := m.ensureRow(k)

	if vi := m.rows[slot].i2; vi != 0 {
		m.vals2[vi] = v

		return
	}

	if len(m.vals2) == 0 {
		m.vals2 = append(m.vals2, *new(V2)) // reserve slot 0 as the absent sentinel
	}

	m.vals2 = append(m.vals2, v)
	m.rows[slot].i2 = uint32(len(m.vals2) - 1)
}

// Get3 returns column 3's value for k and whether that column is present.
func (m *DenseMap3[K, V1, V2, V3]) Get3(k K) (V3, bool) {
	if slot := m.rowSlot(k); slot != 0 {
		if vi := m.rows[slot].i3; vi != 0 {
			return m.vals3[vi], true
		}
	}

	var zero V3

	return zero, false
}

// Put3 sets column 3's value for k.
func (m *DenseMap3[K, V1, V2, V3]) Put3(k K, v V3) {
	slot := m.ensureRow(k)

	if vi := m.rows[slot].i3; vi != 0 {
		m.vals3[vi] = v

		return
	}

	if len(m.vals3) == 0 {
		m.vals3 = append(m.vals3, *new(V3)) // reserve slot 0 as the absent sentinel
	}

	m.vals3 = append(m.vals3, v)
	m.rows[slot].i3 = uint32(len(m.vals3) - 1)
}

// Len reports the number of distinct keys stored (a key counts once any of
// its columns has been set).
func (m *DenseMap3[K, V1, V2, V3]) Len() int {
	if len(m.rows) == 0 {
		return 0
	}

	return len(m.rows) - 1
}
