// Code generated by dev/gen_densemap.py; DO NOT EDIT.

package main

import "testing"

func TestDenseMap2_IndependentColumns(t *testing.T) {
	var m DenseMap2[STR, int, int]

	// Set exactly one column per key (key 0 exercises the slot-0 sentinel).
	m.Put1(0, 100)
	m.Put2(1, 200)

	if m.Len() != 2 {
		t.Fatalf("Len = %d, want 2", m.Len())
	}

	// Each key has only its own column present; all others read absent.
	if got, ok := m.Get1(0); !ok || got != 100 {
		t.Fatalf("Get1(0) = (%d, %v), want (100, true)", got, ok)
	}
	if _, ok := m.Get2(0); ok {
		t.Fatalf("Get2(0) present, want absent")
	}
	if got, ok := m.Get2(1); !ok || got != 200 {
		t.Fatalf("Get2(1) = (%d, %v), want (200, true)", got, ok)
	}
	if _, ok := m.Get1(1); ok {
		t.Fatalf("Get1(1) present, want absent")
	}
}

func TestDenseMap2_AllColumnsOneKey(t *testing.T) {
	var m DenseMap2[STR, int, int]
	const k = 1000

	m.Put1(k, 1)
	m.Put2(k, 2)

	if got, ok := m.Get1(k); !ok || got != 1 {
		t.Fatalf("Get1(k) = (%d, %v), want (1, true)", got, ok)
	}
	if got, ok := m.Get2(k); !ok || got != 2 {
		t.Fatalf("Get2(k) = (%d, %v), want (2, true)", got, ok)
	}

	if m.Len() != 1 {
		t.Fatalf("Len = %d, want 1", m.Len())
	}
}

func TestDenseMap2_OverwriteAndAbsent(t *testing.T) {
	var m DenseMap2[STR, int, int]

	if _, ok := m.Get1(0); ok {
		t.Fatal("empty map reported key 0 present")
	}
	if _, ok := m.Get1(1 << 20); ok {
		t.Fatal("empty map reported out-of-range key present")
	}

	m.Put1(7, 1)
	m.Put1(7, 2)
	m.Put1(7, 3)

	if got, _ := m.Get1(7); got != 3 {
		t.Fatalf("Get1(7) = %d, want 3 (last write)", got)
	}
	if m.Len() != 1 {
		t.Fatalf("Len = %d, want 1 (overwrite must not add a key)", m.Len())
	}
}
