package main

import (
	encb64 "encoding/base64"
	"slices"
	"strings"
	"testing"
)

// A PROTO_LIBRARY whose SRCS(X.proto) is build-generated by a RUN_PROGRAM
// STDOUT_NOAUTO step routes its python output through upstream's bare-token
// path: pb2_arg uses to_build_root(X.proto)==X.proto (not is_arc_src), so the
// PY_SRCS token is the bare `X__intpy3___pb2.py`. That bare token, with no
// `/`, makes uniq_suffix empty (no `.kqhj` yapyc3 suffix) and — carrying no
// `${ARCADIA_BUILD_ROOT}` literal — embeds the resource via objcopy, NOT the
// rescompiler `_raw.auxcpp` path that checked-in protos use. The PB and py3cc
// nodes also carry the generated `.proto` producer's transitive `$(S)` closure
// (its OUTPUT_INCLUDES protos). Mirrors sg7
// irt/bannerland/proto/banner_flags.
func TestEmitPyProto_GeneratedProtoBareTokenObjcopyRouting(t *testing.T) {
	const modPath = "irt/test/banner_flags"
	const consumer = "irt/test/app"

	files := map[string]string{
		consumer + "/ya.make": `PY3_LIBRARY()
NO_LIBC()
NO_RUNTIME()
NO_UTIL()
NO_PYTHON_INCLUDES()
PEERDIR(` + modPath + `)
END()
`,
		modPath + "/ya.make": `PROTO_LIBRARY()
NO_MYPY()
IF (GEN_PROTO)
RUN_PROGRAM(
    ` + modPath + `/gen
    STDOUT_NOAUTO banner_flags.proto
    OUTPUT_INCLUDES dep/markup.proto
)
ENDIF()
SRCS(banner_flags.proto)
EXCLUDE_TAGS(GO_PROTO JAVA_PROTO)
END()
`,
		"dep/markup.proto":                "syntax = \"proto3\";\nmessage Markup { int32 x = 1; }\n",
		"contrib/libs/protobuf/ya.make":   "LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PLATFORM()\nSRCS(p.cpp)\nEND()\n",
		"contrib/python/protobuf/ya.make": "PY3_LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PYTHON_INCLUDES()\nEND()\n",
		"contrib/libs/python/ya.make":     "LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PLATFORM()\nEND()\n",
	}
	writeToolProgram(files, "contrib/tools/protoc", "protoc")
	writeToolProgram(files, "contrib/tools/protoc/plugins/cpp_styleguide", "cpp_styleguide")
	writeToolProgram(files, "tools/py3cc", "py3cc")
	writeToolProgram(files, "tools/py3cc/slow", "slow")
	writeToolProgram(files, "tools/rescompiler", "rescompiler")
	writeToolProgram(files, "tools/rescompressor", "rescompressor")
	writeToolProgram(files, "tools/archiver", "archiver")
	writeToolProgram(files, modPath+"/gen", "gen")

	g := testGen(newMemFS(files), consumer)

	pyOut := "$(B)/" + modPath + "/banner_flags__intpy3___pb2.py"
	yapyc3 := pyOut + ".yapyc3"
	kqhj := pyOut + ".kqhj.yapyc3"

	// (1) No rescompiler `_raw.auxcpp` for the generated proto resources.
	for _, n := range g.Graph {
		if len(n.Outputs) == 0 {
			continue
		}
		o := n.Outputs[0].string()
		if strings.HasPrefix(o, "$(B)/"+modPath+"/") && strings.Contains(o, "_raw.auxcpp") {
			t.Fatalf("generated proto produced a rescompiler aux node %q; want objcopy resfs", o)
		}
	}

	// (2) py3cc emits the bare, unsuffixed yapyc3 (no path-id .kqhj).
	if nodeByOutput(g, kqhj) != nil {
		t.Fatalf("py3cc emitted a path-id-suffixed yapyc3 %q; generated proto must be unsuffixed", kqhj)
	}
	py3cc := mustNodeByOutput(t, g, yapyc3)
	if first := prCmdArgStrings(py3cc); !slices.Contains(first, "banner_flags__intpy3___pb2.py-") {
		t.Fatalf("py3cc first token is not the bare `banner_flags__intpy3___pb2.py-`: %v", first)
	}

	// (3a) The generated `.proto` producer carries the CPP_PROTO submodule tag.
	producer := mustNodeByOutput(t, g, "$(B)/"+modPath+"/banner_flags.proto")
	if producer.TargetProperties.ModuleTag != tagCppProto {
		t.Fatalf("generated .proto producer module_tag = %q; want cpp_proto", producer.TargetProperties.ModuleTag.string())
	}

	// (3) Producer closure rides the PB and py3cc nodes.
	pb := mustNodeByOutput(t, g, pyOut)
	for _, n := range []*Node{pb, py3cc} {
		if !nodeHasInput(n, "$(S)/dep/markup.proto") {
			t.Fatalf("node producing %v is missing producer-closure input $(S)/dep/markup.proto: %v",
				n.Outputs, n.flatInputs())
		}
	}

	// (4) objcopy resfs node: byte-exact hash over the bare tokens + PY3_PROTO tag.
	pb2Key := "resfs/file/py/" + modPath + "/banner_flags_pb2.py"
	yapKey := pb2Key + ".yapyc3"
	bare := []string{"banner_flags__intpy3___pb2.py", "banner_flags__intpy3___pb2.py.yapyc3"}
	keysB64 := []string{
		encb64.StdEncoding.EncodeToString([]byte(pb2Key)),
		encb64.StdEncoding.EncodeToString([]byte(yapKey)),
	}
	kvsHash := []string{
		"resfs/src/" + pb2Key + "=${rootrel;context=TEXT;input=TEXT:\"banner_flags__intpy3___pb2.py\"}",
		"resfs/src/" + yapKey + "=${rootrel;context=TEXT;input=TEXT:\"banner_flags__intpy3___pb2.py.yapyc3\"}",
	}
	wantHash := objcopyHash(bare, keysB64, kvsHash, modPath, stringPtr("PY3_PROTO"))
	wantObjcopy := "$(B)/" + modPath + "/objcopy_" + wantHash + ".o"

	objcopy := nodeByOutput(g, wantObjcopy)
	if objcopy == nil {
		t.Fatalf("graph is missing generated-proto objcopy %q\nobjcopy nodes: %v", wantObjcopy, objcopyOutputs(g))
	}
	if !nodeHasInput(objcopy, pyOut) || !nodeHasInput(objcopy, yapyc3) {
		t.Fatalf("objcopy inputs missing generated py/yapyc3 from $(B): %#v", objcopy.flatInputs())
	}
	deps := graphDeps(g, objcopy)
	if !slices.Contains(deps, pb.UID) {
		t.Fatalf("objcopy deps %v missing PB producer uid %q", deps, pb.UID)
	}
	if !slices.Contains(deps, py3cc.UID) {
		t.Fatalf("objcopy deps %v missing py3cc producer uid %q", deps, py3cc.UID)
	}

	// (5) The module's global archive links the objcopy, not an auxcpp `.pic.o`.
	globalAr := mustNodeByOutput(t, g, "$(B)/"+modPath+"/libpy3irt-test-banner_flags.global.a")
	arArgs := prCmdArgStrings(globalAr)
	if !slices.Contains(arArgs, wantObjcopy) {
		t.Fatalf("global archive does not link the generated-proto objcopy %q: %v", wantObjcopy, arArgs)
	}
	for _, a := range arArgs {
		if strings.Contains(a, "_raw.auxcpp") {
			t.Fatalf("global archive still links an auxcpp member %q for a generated proto", a)
		}
	}
}

// A PROTO_LIBRARY that calls PROTOC_FATAL_WARNINGS() appends `--fatal_warnings`
// to _PROTOC_FLAGS (proto.conf:144). The python proto command base
// _PY_PROTO_CMD_BASE (proto.conf:516) renders `$_PROTOC_FLAGS` after
// `--python_out=$ARCADIA_BUILD_ROOT/$PROTO_NAMESPACE` and before the trailing
// source token — exactly as the cpp side appends d.protocFlags after --cpp_out.
// A sibling PROTO_LIBRARY without the macro must NOT carry the flag. Mirrors
// sg7 sprav/protos (PROTOC_FATAL_WARNINGS on altay_api__intpy3___pb2.py).
func TestEmitPyProto_ProtocFatalWarningsRidesPyCommand(t *testing.T) {
	const fwPath = "sprav/test/protos"
	const plainPath = "sprav/test/plain"
	const consumer = "sprav/test/app"

	files := map[string]string{
		consumer + "/ya.make": `PY3_LIBRARY()
NO_LIBC()
NO_RUNTIME()
NO_UTIL()
NO_PYTHON_INCLUDES()
PEERDIR(` + fwPath + ` ` + plainPath + `)
END()
`,
		fwPath + "/ya.make": `PROTO_LIBRARY()
PROTOC_FATAL_WARNINGS()
SRCS(altay_api.proto)
EXCLUDE_TAGS(GO_PROTO JAVA_PROTO)
END()
`,
		plainPath + "/ya.make": `PROTO_LIBRARY()
SRCS(plain.proto)
EXCLUDE_TAGS(GO_PROTO JAVA_PROTO)
END()
`,
		fwPath + "/altay_api.proto":       "syntax = \"proto3\";\nmessage AltayApi { int32 x = 1; }\n",
		plainPath + "/plain.proto":        "syntax = \"proto3\";\nmessage Plain { int32 x = 1; }\n",
		"contrib/libs/protobuf/ya.make":   "LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PLATFORM()\nSRCS(p.cpp)\nEND()\n",
		"contrib/python/protobuf/ya.make": "PY3_LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PYTHON_INCLUDES()\nEND()\n",
		"contrib/libs/python/ya.make":     "LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PLATFORM()\nEND()\n",
	}
	writeToolProgram(files, "contrib/tools/protoc", "protoc")
	writeToolProgram(files, "contrib/tools/protoc/plugins/cpp_styleguide", "cpp_styleguide")
	writeToolProgram(files, "contrib/python/mypy-protobuf/bin/protoc-gen-mypy", "protoc-gen-mypy")
	writeToolProgram(files, "tools/py3cc", "py3cc")
	writeToolProgram(files, "tools/py3cc/slow", "slow")
	writeToolProgram(files, "tools/rescompiler", "rescompiler")
	writeToolProgram(files, "tools/rescompressor", "rescompressor")
	writeToolProgram(files, "tools/archiver", "archiver")

	g := testGen(newMemFS(files), consumer)

	// The fatal-warnings module's py PB node (and its .pyi share the same node)
	// must carry --fatal_warnings, positioned after --python_out and before the
	// trailing source token.
	fwPy := mustNodeByOutput(t, g, "$(B)/"+fwPath+"/altay_api__intpy3___pb2.py")
	args := prCmdArgStrings(fwPy)
	fwIdx := slices.Index(args, "--fatal_warnings")
	if fwIdx < 0 {
		t.Fatalf("py PB command for PROTOC_FATAL_WARNINGS module missing --fatal_warnings: %v", args)
	}
	var pyOutIdx, srcIdx int = -1, -1
	for i, a := range args {
		if strings.HasPrefix(a, "--python_out=") {
			pyOutIdx = i
		}
		if a == fwPath+"/altay_api.proto" && pyOutIdx >= 0 {
			srcIdx = i
		}
	}
	if !(pyOutIdx >= 0 && pyOutIdx < fwIdx) {
		t.Fatalf("--fatal_warnings (idx %d) must follow --python_out (idx %d): %v", fwIdx, pyOutIdx, args)
	}
	if !(srcIdx >= 0 && fwIdx < srcIdx) {
		t.Fatalf("--fatal_warnings (idx %d) must precede source token (idx %d): %v", fwIdx, srcIdx, args)
	}

	// The .pyi rides the same command (single PB node with .py/.pyi outputs).
	if mustNodeByAnyOutput(t, g, "$(B)/"+fwPath+"/altay_api__intpy3___pb2.pyi") != fwPy {
		t.Fatalf(".pyi output is not produced by the same PB node as the .py")
	}

	// The plain sibling (no macro) must NOT carry the flag.
	plainPy := mustNodeByOutput(t, g, "$(B)/"+plainPath+"/plain__intpy3___pb2.py")
	if slices.Contains(prCmdArgStrings(plainPy), "--fatal_warnings") {
		t.Fatalf("py PB command for non-macro module must NOT carry --fatal_warnings: %v", prCmdArgStrings(plainPy))
	}
}

// Guard: an ordinary checked-in PROTO_LIBRARY SRCS(foo.proto) stays on the
// rescompiler `_raw.auxcpp` resource path with a path-id-suffixed yapyc3 — it
// must NOT be re-routed to objcopy by the generated-proto handling.
func TestEmitPyProto_CheckedInProtoStaysOnRawAux(t *testing.T) {
	const modPath = "irt/test/checked"
	const consumer = "irt/test/checkedapp"

	files := map[string]string{
		consumer + "/ya.make": `PY3_LIBRARY()
NO_LIBC()
NO_RUNTIME()
NO_UTIL()
NO_PYTHON_INCLUDES()
PEERDIR(` + modPath + `)
END()
`,
		modPath + "/ya.make": `PROTO_LIBRARY()
NO_MYPY()
SRCS(foo.proto)
EXCLUDE_TAGS(GO_PROTO JAVA_PROTO)
END()
`,
		modPath + "/foo.proto":            "syntax = \"proto3\";\nmessage Foo { int32 x = 1; }\n",
		"contrib/libs/protobuf/ya.make":   "LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PLATFORM()\nSRCS(p.cpp)\nEND()\n",
		"contrib/python/protobuf/ya.make": "PY3_LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PYTHON_INCLUDES()\nEND()\n",
		"contrib/libs/python/ya.make":     "LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PLATFORM()\nEND()\n",
	}
	writeToolProgram(files, "contrib/tools/protoc", "protoc")
	writeToolProgram(files, "contrib/tools/protoc/plugins/cpp_styleguide", "cpp_styleguide")
	writeToolProgram(files, "tools/py3cc", "py3cc")
	writeToolProgram(files, "tools/py3cc/slow", "slow")
	writeToolProgram(files, "tools/rescompiler", "rescompiler")
	writeToolProgram(files, "tools/rescompressor", "rescompressor")
	writeToolProgram(files, "tools/archiver", "archiver")

	g := testGen(newMemFS(files), consumer)

	sawAux := false
	for _, n := range g.Graph {
		if len(n.Outputs) == 0 {
			continue
		}
		o := n.Outputs[0].string()
		if strings.HasPrefix(o, "$(B)/"+modPath+"/") && strings.HasSuffix(o, "_raw.auxcpp") {
			sawAux = true
		}
		if strings.HasPrefix(o, "$(B)/"+modPath+"/objcopy_") {
			t.Fatalf("checked-in proto routed to objcopy resfs %q; want _raw.auxcpp", o)
		}
	}
	if !sawAux {
		t.Fatal("checked-in proto did not produce the expected _raw.auxcpp resource node")
	}

	// The path-id-suffixed yapyc3 is the checked-in form.
	pyRel := "$(B)/" + modPath + "/foo__intpy3___pb2.py"
	suffix := protoPySuffix(modPath)
	if nodeByOutput(g, pyRel+"."+suffix+".yapyc3") == nil {
		t.Fatalf("checked-in proto missing path-id-suffixed yapyc3 %q", pyRel+"."+suffix+".yapyc3")
	}
}
