package main

import (
	"strings"
	"testing"
)

// TestEmitProtoSrcs_GeneratedProtoWiresProducerDep reproduces the
// jsonpath G2 gap: a PROTO_LIBRARY whose SRCS(X.proto) is itself the OUT
// of a RUN_ANTLR (no X.proto in source tree). The PB protoc node must wire
// a dep to the JV producer of X.proto AND treat the input as build-rooted,
// or the JV (and its CF dep on protobuf.stg) get DFS-pruned at finalize.
func TestEmitProtoSrcs_GeneratedProtoWiresProducerDep(t *testing.T) {
	const modPath = "yql/essentials/parser/proto_ast/gen/jsonpath"

	files := map[string]string{}
	writeToolProgram(files, "contrib/tools/protoc", "protoc")
	writeToolProgram(files, "contrib/tools/protoc/plugins/cpp_styleguide", "cpp_styleguide")
	for path, body := range map[string]string{
		modPath + "/ya.make": `PROTO_LIBRARY()

IF (GEN_PROTO)
    SET(antlr_output ${ARCADIA_BUILD_ROOT}/${MODDIR})
    SET(antlr_templates ${antlr_output}/org/antlr/codegen/templates)
    SET(jsonpath_grammar ${ARCADIA_ROOT}/yql/essentials/minikql/jsonpath/JsonPath.g)

    CONFIGURE_FILE(${ARCADIA_ROOT}/templates/protobuf.stg.in ${antlr_templates}/protobuf/protobuf.stg)

    RUN_ANTLR(
        ${jsonpath_grammar}
        -lib .
        -fo ${antlr_output}
        -language protobuf
        IN ${jsonpath_grammar} ${antlr_templates}/protobuf/protobuf.stg
        OUT_NOAUTO JsonPathParser.proto
        CWD ${antlr_output}
    )
ENDIF()

SRCS(JsonPathParser.proto)

EXCLUDE_TAGS(GO_PROTO JAVA_PROTO)

END()
`,
		"templates/protobuf.stg.in":                  "stub stg\n",
		"yql/essentials/minikql/jsonpath/JsonPath.g": "stub grammar\n",
		"contrib/libs/protobuf/ya.make":              "LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PLATFORM()\nSRCS(p.cpp)\nEND()\n",
	} {
		files[path] = body
	}

	g := testGen(newMemFS(files), modPath)

	byOut := make(map[string]*Node, len(g.Graph))
	for _, n := range g.Graph {
		if len(n.Outputs) > 0 {
			byOut[n.Outputs[0].String()] = n
		}
	}

	for _, key := range []string{
		"$(B)/" + modPath + "/JsonPathParser.proto",
		"$(B)/" + modPath + "/org/antlr/codegen/templates/protobuf/protobuf.stg",
	} {
		if byOut[key] == nil {
			t.Errorf("graph missing reachable node with output %q", key)
		}
	}

	var pb *Node
	for _, n := range g.Graph {
		if n.KV.P == pkPB && strings.HasSuffix(n.Outputs[0].String(), "JsonPathParser.pb.h") {
			pb = n
			break
		}
	}
	if pb == nil {
		t.Fatal("no PB node for JsonPathParser.pb.h emitted")
	}

	jv := byOut["$(B)/"+modPath+"/JsonPathParser.proto"]
	if jv == nil {
		t.Fatal("no JV node producing JsonPathParser.proto")
	}
	if jv.KV.P != pkJV {
		t.Errorf("expected JV kv.p, got %v", jv.KV.P)
	}

	found := false
	for _, d := range graphDeps(g, pb) {
		if d == jv.UID {
			found = true
			break
		}
	}
	if !found {
		t.Errorf("graphDeps(g, PB) %v does not include JV(.proto) uid %q", graphDeps(g, pb), jv.UID)
	}

	hasBuildProto := false
	for _, in := range pb.Inputs {
		if in.String() == "$(B)/"+modPath+"/JsonPathParser.proto" {
			hasBuildProto = true
			break
		}
	}
	if !hasBuildProto {
		t.Errorf("PB.Inputs does not include $(B)/.../JsonPathParser.proto: %v", pb.Inputs)
	}
}

// TestEmitProtoSrcs_GeneratedProtoInheritsProducerSourceInputs locks the
// transitive source closure: when SRCS(X.proto) is build-generated by a
// RUN_ANTLR (JV) step, the PB protoc node's inputs must include the JV
// producer's $(S) leaf sources (grammar, CONFIGURE_FILE source, antlr.jar,
// and the wrapper scripts), exactly as upstream tracks them — otherwise the
// PB self_uid diverges and the drift cascades to .pb.cc.o and the proto AR.
func TestEmitProtoSrcs_GeneratedProtoInheritsProducerSourceInputs(t *testing.T) {
	const modPath = "yql/essentials/parser/proto_ast/gen/jsonpath"

	files := map[string]string{}
	writeToolProgram(files, "contrib/tools/protoc", "protoc")
	writeToolProgram(files, "contrib/tools/protoc/plugins/cpp_styleguide", "cpp_styleguide")
	for path, body := range map[string]string{
		modPath + "/ya.make": `PROTO_LIBRARY()

IF (GEN_PROTO)
    SET(antlr_output ${ARCADIA_BUILD_ROOT}/${MODDIR})
    SET(antlr_templates ${antlr_output}/org/antlr/codegen/templates)
    SET(jsonpath_grammar ${ARCADIA_ROOT}/yql/essentials/minikql/jsonpath/JsonPath.g)

    CONFIGURE_FILE(${ARCADIA_ROOT}/templates/protobuf.stg.in ${antlr_templates}/protobuf/protobuf.stg)

    RUN_ANTLR(
        ${jsonpath_grammar}
        -lib .
        -fo ${antlr_output}
        -language protobuf
        IN ${jsonpath_grammar} ${antlr_templates}/protobuf/protobuf.stg
        OUT_NOAUTO JsonPathParser.proto
        CWD ${antlr_output}
    )
ENDIF()

SRCS(JsonPathParser.proto)

EXCLUDE_TAGS(GO_PROTO JAVA_PROTO)

END()
`,
		"templates/protobuf.stg.in":                  "stub stg\n",
		"yql/essentials/minikql/jsonpath/JsonPath.g": "stub grammar\n",
		"contrib/libs/protobuf/ya.make":              "LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PLATFORM()\nSRCS(p.cpp)\nEND()\n",
	} {
		files[path] = body
	}

	g := testGen(newMemFS(files), modPath)

	var pb *Node
	for _, n := range g.Graph {
		if n.KV.P == pkPB && strings.HasSuffix(n.Outputs[0].String(), "JsonPathParser.pb.h") {
			pb = n
			break
		}
	}
	if pb == nil {
		t.Fatal("no PB node for JsonPathParser.pb.h emitted")
	}

	have := make(map[string]struct{}, len(pb.Inputs))
	for _, in := range pb.Inputs {
		have[in.String()] = struct{}{}
	}
	for _, want := range []string{
		"$(S)/yql/essentials/minikql/jsonpath/JsonPath.g",
		"$(S)/templates/protobuf.stg.in",
		"$(S)/contrib/java/antlr/antlr3/antlr.jar",
		"$(S)/build/scripts/configure_file.py",
		"$(S)/build/scripts/stdout2stderr.py",
	} {
		if _, ok := have[want]; !ok {
			t.Errorf("PB.Inputs missing producer source input %q: %v", want, vfsStringsT3(pb.Inputs))
		}
	}
}

// TestEmitProtoSrcs_AntlrCppOutsCompileIntoProtoArchive locks the second
// jsonpath G2 leg: RUN_ANTLR(... OUT *.cpp ...) inside a PROTO_LIBRARY's
// IF(GEN_PROTO) block — upstream auto-promotes those .cpp outputs to SRCS,
// compiling them and archiving the .o into the same proto-library AR
// alongside .pb.cc.o (see jsonpath ya.make: SRCS lists only the .proto, but
// JsonPathParser.cpp and JsonPathLexer.cpp from the second RUN_ANTLR land
// in libproto_ast-gen-jsonpath.a).
func TestEmitProtoSrcs_AntlrCppOutsCompileIntoProtoArchive(t *testing.T) {
	const modPath = "yql/essentials/parser/proto_ast/gen/jsonpath"

	files := map[string]string{}
	writeToolProgram(files, "contrib/tools/protoc", "protoc")
	writeToolProgram(files, "contrib/tools/protoc/plugins/cpp_styleguide", "cpp_styleguide")
	for path, body := range map[string]string{
		modPath + "/ya.make": `PROTO_LIBRARY()

IF (GEN_PROTO)
    SET(antlr_output ${ARCADIA_BUILD_ROOT}/${MODDIR})
    SET(antlr_templates ${antlr_output}/org/antlr/codegen/templates)
    SET(jsonpath_grammar ${ARCADIA_ROOT}/yql/essentials/minikql/jsonpath/JsonPath.g)

    CONFIGURE_FILE(${ARCADIA_ROOT}/templates/Cpp.stg.in ${antlr_templates}/Cpp/Cpp.stg)
    CONFIGURE_FILE(${ARCADIA_ROOT}/templates/protobuf.stg.in ${antlr_templates}/protobuf/protobuf.stg)

    RUN_ANTLR(
        ${jsonpath_grammar}
        -lib .
        -fo ${antlr_output}
        -language protobuf
        IN ${jsonpath_grammar} ${antlr_templates}/protobuf/protobuf.stg
        OUT_NOAUTO JsonPathParser.proto
        CWD ${antlr_output}
    )

    RUN_ANTLR(
        ${jsonpath_grammar}
        -lib .
        -fo ${antlr_output}
        IN ${jsonpath_grammar} ${antlr_templates}/Cpp/Cpp.stg
        OUT JsonPathParser.cpp JsonPathLexer.cpp JsonPathParser.h JsonPathLexer.h
        CWD ${antlr_output}
    )
ENDIF()

SRCS(JsonPathParser.proto)

EXCLUDE_TAGS(GO_PROTO JAVA_PROTO)

END()
`,
		"templates/Cpp.stg.in":                       "stub cpp stg\n",
		"templates/protobuf.stg.in":                  "stub protobuf stg\n",
		"yql/essentials/minikql/jsonpath/JsonPath.g": "stub grammar\n",
		"contrib/libs/protobuf/ya.make":              "LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PLATFORM()\nSRCS(p.cpp)\nEND()\n",
	} {
		files[path] = body
	}

	g := testGen(newMemFS(files), modPath)

	byOut := make(map[string]*Node, len(g.Graph))
	for _, n := range g.Graph {
		if len(n.Outputs) > 0 {
			byOut[n.Outputs[0].String()] = n
		}
	}

	for _, key := range []string{
		"$(B)/" + modPath + "/JsonPathLexer.cpp.o",
		"$(B)/" + modPath + "/JsonPathParser.cpp.o",
	} {
		if byOut[key] == nil {
			t.Errorf("graph missing CC node with output %q", key)
		}
	}

	ar := byOut["$(B)/"+modPath+"/libproto_ast-gen-jsonpath.a"]
	if ar == nil {
		t.Fatal("no proto AR node emitted")
	}
	for _, want := range []string{
		"$(B)/" + modPath + "/JsonPathLexer.cpp.o",
		"$(B)/" + modPath + "/JsonPathParser.cpp.o",
		"$(B)/" + modPath + "/JsonPathParser.pb.cc.o",
	} {
		found := false
		for _, in := range ar.Inputs {
			if in.String() == want {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("proto AR inputs missing %q: %v", want, ar.Inputs)
		}
	}

	// Member ORDER: the ANTLR-generated .cpp objects are ordinary translation
	// units (regular archive phase) and upstream lists them BEFORE the proto
	// .pb.cc.o (proto-codegen phase). Reference jsonpath AR order is
	// [JsonPathParser.cpp.o, JsonPathLexer.cpp.o, JsonPathParser.pb.cc.o].
	idxOf := func(rel string) int {
		want := "$(B)/" + modPath + "/" + rel
		for i, in := range ar.Inputs {
			if in.String() == want {
				return i
			}
		}
		return -1
	}
	parserCpp := idxOf("JsonPathParser.cpp.o")
	lexerCpp := idxOf("JsonPathLexer.cpp.o")
	pbCC := idxOf("JsonPathParser.pb.cc.o")
	if parserCpp < 0 || lexerCpp < 0 || pbCC < 0 {
		t.Fatalf("missing AR member (parser=%d lexer=%d pb=%d): %v", parserCpp, lexerCpp, pbCC, ar.Inputs)
	}
	if !(parserCpp < pbCC && lexerCpp < pbCC) {
		t.Errorf("ANTLR .cpp.o must precede .pb.cc.o in proto AR: parser=%d lexer=%d pb.cc=%d (%v)",
			parserCpp, lexerCpp, pbCC, ar.Inputs)
	}
}
