package main

import (
	"strings"
	"testing"
)

// TestEmitProtoSrcs_GeneratedProtoWiresProducerDep reproduces the
// jsonpath G2 gap: a PROTO_LIBRARY whose SRCS(X.proto) is itself the OUT
// of a RUN_ANTLR (no X.proto in source tree). The PB protoc node must wire
// a dep to the JV producer of X.proto AND treat the input as build-rooted,
// or the JV (and its CF dep on protobuf.stg) get DFS-pruned at finalize.
func TestEmitProtoSrcs_GeneratedProtoWiresProducerDep(t *testing.T) {
	const modPath = "yql/essentials/parser/proto_ast/gen/jsonpath"

	files := map[string]string{}
	writeToolProgram(files, "contrib/tools/protoc", "protoc")
	writeToolProgram(files, "contrib/tools/protoc/plugins/cpp_styleguide", "cpp_styleguide")
	for path, body := range map[string]string{
		modPath + "/ya.make": `PROTO_LIBRARY()

IF (GEN_PROTO)
    SET(antlr_output ${ARCADIA_BUILD_ROOT}/${MODDIR})
    SET(antlr_templates ${antlr_output}/org/antlr/codegen/templates)
    SET(jsonpath_grammar ${ARCADIA_ROOT}/yql/essentials/minikql/jsonpath/JsonPath.g)

    CONFIGURE_FILE(${ARCADIA_ROOT}/templates/protobuf.stg.in ${antlr_templates}/protobuf/protobuf.stg)

    RUN_ANTLR(
        ${jsonpath_grammar}
        -lib .
        -fo ${antlr_output}
        -language protobuf
        IN ${jsonpath_grammar} ${antlr_templates}/protobuf/protobuf.stg
        OUT_NOAUTO JsonPathParser.proto
        CWD ${antlr_output}
    )
ENDIF()

SRCS(JsonPathParser.proto)

EXCLUDE_TAGS(GO_PROTO JAVA_PROTO)

END()
`,
		"templates/protobuf.stg.in":                  "stub stg\n",
		"yql/essentials/minikql/jsonpath/JsonPath.g": "stub grammar\n",
		"contrib/libs/protobuf/ya.make":              "LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PLATFORM()\nSRCS(p.cpp)\nEND()\n",
	} {
		files[path] = body
	}

	g := testGen(newMemFS(files), modPath)

	byOut := make(map[string]*Node, len(g.Graph))
	for _, n := range g.Graph {
		if len(n.Outputs) > 0 {
			byOut[n.Outputs[0].string()] = n
		}
	}

	for _, key := range []string{
		"$(B)/" + modPath + "/JsonPathParser.proto",
		"$(B)/" + modPath + "/org/antlr/codegen/templates/protobuf/protobuf.stg",
	} {
		if byOut[key] == nil {
			t.Errorf("graph missing reachable node with output %q", key)
		}
	}

	var pb *Node
	for _, n := range g.Graph {
		if n.KV.P == pkPB && strings.HasSuffix(n.Outputs[0].string(), "JsonPathParser.pb.h") {
			pb = n
			break
		}
	}
	if pb == nil {
		t.Fatal("no PB node for JsonPathParser.pb.h emitted")
	}

	jv := byOut["$(B)/"+modPath+"/JsonPathParser.proto"]
	if jv == nil {
		t.Fatal("no JV node producing JsonPathParser.proto")
	}
	if jv.KV.P != pkJV {
		t.Errorf("expected JV kv.p, got %v", jv.KV.P)
	}

	found := false
	for _, d := range graphDeps(g, pb) {
		if d == jv.UID {
			found = true
			break
		}
	}
	if !found {
		t.Errorf("graphDeps(g, PB) %v does not include JV(.proto) uid %q", graphDeps(g, pb), jv.UID)
	}

	hasBuildProto := false
	for _, in := range pb.flatInputs() {
		if in.string() == "$(B)/"+modPath+"/JsonPathParser.proto" {
			hasBuildProto = true
			break
		}
	}
	if !hasBuildProto {
		t.Errorf("PB.flatInputs() does not include $(B)/.../JsonPathParser.proto: %v", pb.flatInputs())
	}
}

// TestEmitProtoSrcs_GeneratedProtoInheritsProducerSourceInputs locks the
// transitive source closure: when SRCS(X.proto) is build-generated by a
// RUN_ANTLR (JV) step, the PB protoc node's inputs must include the JV
// producer's $(S) leaf sources (grammar, CONFIGURE_FILE source, antlr.jar,
// and the wrapper scripts), exactly as upstream tracks them — otherwise the
// PB self_uid diverges and the drift cascades to .pb.cc.o and the proto AR.
func TestEmitProtoSrcs_GeneratedProtoInheritsProducerSourceInputs(t *testing.T) {
	const modPath = "yql/essentials/parser/proto_ast/gen/jsonpath"

	files := map[string]string{}
	writeToolProgram(files, "contrib/tools/protoc", "protoc")
	writeToolProgram(files, "contrib/tools/protoc/plugins/cpp_styleguide", "cpp_styleguide")
	for path, body := range map[string]string{
		modPath + "/ya.make": `PROTO_LIBRARY()

IF (GEN_PROTO)
    SET(antlr_output ${ARCADIA_BUILD_ROOT}/${MODDIR})
    SET(antlr_templates ${antlr_output}/org/antlr/codegen/templates)
    SET(jsonpath_grammar ${ARCADIA_ROOT}/yql/essentials/minikql/jsonpath/JsonPath.g)

    CONFIGURE_FILE(${ARCADIA_ROOT}/templates/protobuf.stg.in ${antlr_templates}/protobuf/protobuf.stg)

    RUN_ANTLR(
        ${jsonpath_grammar}
        -lib .
        -fo ${antlr_output}
        -language protobuf
        IN ${jsonpath_grammar} ${antlr_templates}/protobuf/protobuf.stg
        OUT_NOAUTO JsonPathParser.proto
        CWD ${antlr_output}
    )
ENDIF()

SRCS(JsonPathParser.proto)

EXCLUDE_TAGS(GO_PROTO JAVA_PROTO)

END()
`,
		"templates/protobuf.stg.in":                  "stub stg\n",
		"yql/essentials/minikql/jsonpath/JsonPath.g": "stub grammar\n",
		"contrib/libs/protobuf/ya.make":              "LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PLATFORM()\nSRCS(p.cpp)\nEND()\n",
	} {
		files[path] = body
	}

	g := testGen(newMemFS(files), modPath)

	var pb *Node
	for _, n := range g.Graph {
		if n.KV.P == pkPB && strings.HasSuffix(n.Outputs[0].string(), "JsonPathParser.pb.h") {
			pb = n
			break
		}
	}
	if pb == nil {
		t.Fatal("no PB node for JsonPathParser.pb.h emitted")
	}

	have := make(map[string]struct{}, len(pb.flatInputs()))
	for _, in := range pb.flatInputs() {
		have[in.string()] = struct{}{}
	}
	for _, want := range []string{
		"$(S)/yql/essentials/minikql/jsonpath/JsonPath.g",
		"$(S)/templates/protobuf.stg.in",
		"$(S)/contrib/java/antlr/antlr3/antlr.jar",
		"$(S)/build/scripts/configure_file.py",
		"$(S)/build/scripts/stdout2stderr.py",
	} {
		if _, ok := have[want]; !ok {
			t.Errorf("PB.flatInputs() missing producer source input %q: %v", want, vfsStringsT3(pb.flatInputs()))
		}
	}
}

// TestEmitProtoSrcs_AntlrCppOutsCompileIntoProtoArchive locks the second
// jsonpath G2 leg: RUN_ANTLR(... OUT *.cpp ...) inside a PROTO_LIBRARY's
// IF(GEN_PROTO) block — upstream auto-promotes those .cpp outputs to SRCS,
// compiling them and archiving the .o into the same proto-library AR
// alongside .pb.cc.o (see jsonpath ya.make: SRCS lists only the .proto, but
// JsonPathParser.cpp and JsonPathLexer.cpp from the second RUN_ANTLR land
// in libproto_ast-gen-jsonpath.a).
func TestEmitProtoSrcs_AntlrCppOutsCompileIntoProtoArchive(t *testing.T) {
	const modPath = "yql/essentials/parser/proto_ast/gen/jsonpath"

	files := map[string]string{}
	writeToolProgram(files, "contrib/tools/protoc", "protoc")
	writeToolProgram(files, "contrib/tools/protoc/plugins/cpp_styleguide", "cpp_styleguide")
	for path, body := range map[string]string{
		modPath + "/ya.make": `PROTO_LIBRARY()

IF (GEN_PROTO)
    SET(antlr_output ${ARCADIA_BUILD_ROOT}/${MODDIR})
    SET(antlr_templates ${antlr_output}/org/antlr/codegen/templates)
    SET(jsonpath_grammar ${ARCADIA_ROOT}/yql/essentials/minikql/jsonpath/JsonPath.g)

    CONFIGURE_FILE(${ARCADIA_ROOT}/templates/Cpp.stg.in ${antlr_templates}/Cpp/Cpp.stg)
    CONFIGURE_FILE(${ARCADIA_ROOT}/templates/protobuf.stg.in ${antlr_templates}/protobuf/protobuf.stg)

    RUN_ANTLR(
        ${jsonpath_grammar}
        -lib .
        -fo ${antlr_output}
        -language protobuf
        IN ${jsonpath_grammar} ${antlr_templates}/protobuf/protobuf.stg
        OUT_NOAUTO JsonPathParser.proto
        CWD ${antlr_output}
    )

    RUN_ANTLR(
        ${jsonpath_grammar}
        -lib .
        -fo ${antlr_output}
        IN ${jsonpath_grammar} ${antlr_templates}/Cpp/Cpp.stg
        OUT JsonPathParser.cpp JsonPathLexer.cpp JsonPathParser.h JsonPathLexer.h
        CWD ${antlr_output}
    )
ENDIF()

SRCS(JsonPathParser.proto)

EXCLUDE_TAGS(GO_PROTO JAVA_PROTO)

END()
`,
		"templates/Cpp.stg.in":                       "stub cpp stg\n",
		"templates/protobuf.stg.in":                  "stub protobuf stg\n",
		"yql/essentials/minikql/jsonpath/JsonPath.g": "stub grammar\n",
		"contrib/libs/protobuf/ya.make":              "LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PLATFORM()\nSRCS(p.cpp)\nEND()\n",
	} {
		files[path] = body
	}

	g := testGen(newMemFS(files), modPath)

	byOut := make(map[string]*Node, len(g.Graph))
	for _, n := range g.Graph {
		if len(n.Outputs) > 0 {
			byOut[n.Outputs[0].string()] = n
		}
	}

	for _, key := range []string{
		"$(B)/" + modPath + "/JsonPathLexer.cpp.o",
		"$(B)/" + modPath + "/JsonPathParser.cpp.o",
	} {
		if byOut[key] == nil {
			t.Errorf("graph missing CC node with output %q", key)
		}
	}

	ar := byOut["$(B)/"+modPath+"/libproto_ast-gen-jsonpath.a"]
	if ar == nil {
		t.Fatal("no proto AR node emitted")
	}
	for _, want := range []string{
		"$(B)/" + modPath + "/JsonPathLexer.cpp.o",
		"$(B)/" + modPath + "/JsonPathParser.cpp.o",
		"$(B)/" + modPath + "/JsonPathParser.pb.cc.o",
	} {
		found := false
		for _, in := range ar.flatInputs() {
			if in.string() == want {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("proto AR inputs missing %q: %v", want, ar.flatInputs())
		}
	}

	// Member ORDER: the ANTLR-generated .cpp objects are ordinary translation
	// units (regular archive phase) and upstream lists them BEFORE the proto
	// .pb.cc.o (proto-codegen phase). Reference jsonpath AR order is
	// [JsonPathParser.cpp.o, JsonPathLexer.cpp.o, JsonPathParser.pb.cc.o].
	idxOf := func(rel string) int {
		want := "$(B)/" + modPath + "/" + rel
		for i, in := range ar.flatInputs() {
			if in.string() == want {
				return i
			}
		}
		return -1
	}
	parserCpp := idxOf("JsonPathParser.cpp.o")
	lexerCpp := idxOf("JsonPathLexer.cpp.o")
	pbCC := idxOf("JsonPathParser.pb.cc.o")
	if parserCpp < 0 || lexerCpp < 0 || pbCC < 0 {
		t.Fatalf("missing AR member (parser=%d lexer=%d pb=%d): %v", parserCpp, lexerCpp, pbCC, ar.flatInputs())
	}
	if !(parserCpp < pbCC && lexerCpp < pbCC) {
		t.Errorf("ANTLR .cpp.o must precede .pb.cc.o in proto AR: parser=%d lexer=%d pb.cc=%d (%v)",
			parserCpp, lexerCpp, pbCC, ar.flatInputs())
	}
}

// TestEmitPyProtoSrc_GeneratedProtoWiresProducerDep is the Python protobuf
// analogue of TestEmitProtoSrcs_GeneratedProtoWiresProducerDep: a PROTO_LIBRARY
// whose SRCS(X.proto) is the OUT of a RUN_ANTLR (no on-disk X.proto), consumed
// by a PY3_LIBRARY. Upstream wires the python protoc (PB) node to the build-tree
// proto, takes the producer dependency, and carries the producer's $(S) leaf
// sources. Before the fix the py PB node listed $(S)/.../JsonPathParser.proto —
// a nonexistent source path that faults sandboxing content-hashing — with no
// producer dep and no producer source inputs.
func TestEmitPyProtoSrc_GeneratedProtoWiresProducerDep(t *testing.T) {
	const modPath = "yql/essentials/parser/proto_ast/gen/jsonpath"
	const consumer = "app/pytool"

	files := map[string]string{}
	writeToolProgram(files, "contrib/tools/protoc", "protoc")
	writeToolProgram(files, "contrib/tools/protoc/plugins/cpp_styleguide", "cpp_styleguide")
	writeToolProgram(files, "tools/py3cc", "py3cc")
	writeToolProgram(files, "tools/py3cc/slow", "py3cc_slow")
	writeToolProgram(files, "tools/rescompiler", "rescompiler")
	for path, body := range map[string]string{
		consumer + "/ya.make": `PY3_LIBRARY()
NO_LIBC()
NO_RUNTIME()
NO_UTIL()
NO_PYTHON_INCLUDES()
PEERDIR(` + modPath + `)
END()
`,
		modPath + "/ya.make": `PROTO_LIBRARY()
NO_MYPY()

IF (GEN_PROTO)
    SET(antlr_output ${ARCADIA_BUILD_ROOT}/${MODDIR})
    SET(antlr_templates ${antlr_output}/org/antlr/codegen/templates)
    SET(jsonpath_grammar ${ARCADIA_ROOT}/yql/essentials/minikql/jsonpath/JsonPath.g)

    CONFIGURE_FILE(${ARCADIA_ROOT}/templates/protobuf.stg.in ${antlr_templates}/protobuf/protobuf.stg)

    RUN_ANTLR(
        ${jsonpath_grammar}
        -lib .
        -fo ${antlr_output}
        -language protobuf
        IN ${jsonpath_grammar} ${antlr_templates}/protobuf/protobuf.stg
        OUT_NOAUTO JsonPathParser.proto
        CWD ${antlr_output}
    )
ENDIF()

SRCS(JsonPathParser.proto)

EXCLUDE_TAGS(GO_PROTO JAVA_PROTO)

END()
`,
		"templates/protobuf.stg.in":                  "stub stg\n",
		"yql/essentials/minikql/jsonpath/JsonPath.g": "stub grammar\n",
		"contrib/libs/protobuf/ya.make":              "LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PLATFORM()\nSRCS(p.cpp)\nEND()\n",
		"contrib/python/protobuf/ya.make":            "PY3_LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PYTHON_INCLUDES()\nEND()\n",
		"contrib/libs/python/ya.make":                "LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PLATFORM()\nEND()\n",
	} {
		files[path] = body
	}

	g := testGen(newMemFS(files), consumer)

	var pyPB *Node
	for _, n := range g.Graph {
		if n.KV.P == pkPB && n.TargetProperties.ModuleTag == tagPy3Proto &&
			strings.HasSuffix(n.Outputs[0].string(), "JsonPathParser__intpy3___pb2.py") {
			pyPB = n
			break
		}
	}
	if pyPB == nil {
		t.Fatal("no python PB node for JsonPathParser__intpy3___pb2.py emitted")
	}

	byOut := make(map[string]*Node, len(g.Graph))
	for _, n := range g.Graph {
		if len(n.Outputs) > 0 {
			byOut[n.Outputs[0].string()] = n
		}
	}
	jv := byOut["$(B)/"+modPath+"/JsonPathParser.proto"]
	if jv == nil {
		t.Fatal("no JV node producing JsonPathParser.proto")
	}

	// (1) build-tree proto input, not the nonexistent $(S) source.
	hasBuildProto := false
	hasSourceProto := false
	for _, in := range pyPB.flatInputs() {
		switch in.string() {
		case "$(B)/" + modPath + "/JsonPathParser.proto":
			hasBuildProto = true
		case "$(S)/" + modPath + "/JsonPathParser.proto":
			hasSourceProto = true
		}
	}
	if !hasBuildProto {
		t.Errorf("py PB.flatInputs() does not include $(B)/.../JsonPathParser.proto: %v", vfsStringsT3(pyPB.flatInputs()))
	}
	if hasSourceProto {
		t.Errorf("py PB.flatInputs() still lists the nonexistent $(S)/.../JsonPathParser.proto: %v", vfsStringsT3(pyPB.flatInputs()))
	}

	// (2) producer dependency.
	found := false
	for _, d := range graphDeps(g, pyPB) {
		if d == jv.UID {
			found = true
			break
		}
	}
	if !found {
		t.Errorf("graphDeps(g, pyPB) %v does not include JV(.proto) uid %q", graphDeps(g, pyPB), jv.UID)
	}

	// (3) producer source inputs ride on the py PB node's flat inputs.
	have := make(map[string]struct{}, len(pyPB.flatInputs()))
	for _, in := range pyPB.flatInputs() {
		have[in.string()] = struct{}{}
	}
	for _, want := range []string{
		"$(S)/yql/essentials/minikql/jsonpath/JsonPath.g",
		"$(S)/templates/protobuf.stg.in",
		"$(S)/contrib/java/antlr/antlr3/antlr.jar",
		"$(S)/build/scripts/configure_file.py",
		"$(S)/build/scripts/stdout2stderr.py",
	} {
		if _, ok := have[want]; !ok {
			t.Errorf("py PB.flatInputs() missing producer source input %q: %v", want, vfsStringsT3(pyPB.flatInputs()))
		}
	}
}

// TestEmitProtoSrcs_SetAppendProtoFilesNotDoubled reproduces the grut auxiliary
// duplicate-PB-producer abort (T-14). A PROTO_LIBRARY that builds its proto list
// with SET_APPEND(PROTO_FILES …) and feeds it to SRCS(${PROTO_FILES}) is
// collected twice by genModule: a probe pass to learn the module type, then a
// cpp-proto re-collect. When the re-collect env is cloned from the probe-mutated
// env, SET_APPEND re-appends PROTO_FILES (VAR = "$VAR x"), doubling the list, so
// the same proto is scheduled for PB generation twice and CodegenRegistry aborts
// on the duplicate producer. The re-collect must start from a clean module base
// env, so each proto yields exactly one PB producer.
func TestEmitProtoSrcs_SetAppendProtoFilesNotDoubled(t *testing.T) {
	const modPath = "grut/libs/proto/public/auxiliary"

	files := map[string]string{}
	writeToolProgram(files, "contrib/tools/protoc", "protoc")
	writeToolProgram(files, "contrib/tools/protoc/plugins/cpp_styleguide", "cpp_styleguide")
	for path, body := range map[string]string{
		modPath + "/ya.make": `PROTO_LIBRARY()

SET_APPEND(PROTO_FILES
    foo.proto
)

SRCS(${PROTO_FILES})

LIST_PROTO(${PROTO_FILES})

EXCLUDE_TAGS(GO_PROTO JAVA_PROTO)

END()
`,
		modPath + "/foo.proto":          "syntax = \"proto3\";\npackage grut.auxiliary;\n",
		"contrib/libs/protobuf/ya.make": "LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PLATFORM()\nSRCS(p.cpp)\nEND()\n",
	} {
		files[path] = body
	}

	g := testGen(newMemFS(files), modPath)

	var pbH, pbCC int
	for _, n := range g.Graph {
		if n.KV.P != pkPB {
			continue
		}
		for _, out := range n.Outputs {
			switch out.string() {
			case "$(B)/" + modPath + "/foo.pb.h":
				pbH++
			case "$(B)/" + modPath + "/foo.pb.cc":
				pbCC++
			}
		}
	}

	if pbH != 1 {
		t.Errorf("expected exactly one PB producer for foo.pb.h, got %d", pbH)
	}
	if pbCC != 1 {
		t.Errorf("expected exactly one PB producer for foo.pb.cc, got %d", pbCC)
	}
}

// TestGen_PyProtoLibrary_TransitivePROTONamespaceReachesPyProtoCmd reproduces the
// sg7 brandformance py3_proto gap: a PY-addressed PROTO_LIBRARY reaching a
// transitive PROTO_LIBRARY that declares a bare (non-GLOBAL) PROTO_NAMESPACE(yt)
// must carry -I=$(S)/yt in its gen_py_protos protoc command, exactly as the C++
// pb.h side does. The contributor chain mirrors the reference:
// ads/autobudget/protos -> grut/libs/proto/public/metadata -> yt/yt_proto/yt/core
// (PROTO_NAMESPACE(yt)). The reference orders the namespace token after the
// protobuf-src include and before the NEED_GOOGLE_PROTO_PEERDIRS protoc-src
// include, inside the -I block (before --python_out).
func TestGen_PyProtoLibrary_TransitivePROTONamespaceReachesPyProtoCmd(t *testing.T) {
	const consumer = "app/pytool"

	files := map[string]string{}
	writeToolProgram(files, "contrib/tools/protoc", "protoc")
	writeToolProgram(files, "contrib/tools/protoc/plugins/cpp_styleguide", "cpp_styleguide")
	writeToolProgram(files, "tools/py3cc", "py3cc")
	writeToolProgram(files, "tools/py3cc/slow", "py3cc_slow")
	writeToolProgram(files, "tools/rescompiler", "rescompiler")
	writeToolProgram(files, "contrib/python/mypy-protobuf/bin/protoc-gen-mypy", "protoc-gen-mypy")

	writeTestModuleFile(files, "yt/yt_proto/yt/core/ya.make", `PROTO_LIBRARY()
PROTO_NAMESPACE(yt)
SRCS(core.proto)
END()
`)
	writeTestModuleFile(files, "yt/yt_proto/yt/core/core.proto", "syntax = \"proto3\";\npackage yt;\nmessage Core {}\n")

	writeTestModuleFile(files, "grut/libs/proto/public/metadata/ya.make", `PROTO_LIBRARY()
PEERDIR(yt/yt_proto/yt/core)
SRCS(meta.proto)
END()
`)
	writeTestModuleFile(files, "grut/libs/proto/public/metadata/meta.proto", "syntax = \"proto3\";\npackage test;\nmessage Meta {}\n")

	writeTestModuleFile(files, "ads/autobudget/protos/ya.make", `PROTO_LIBRARY()
PEERDIR(grut/libs/proto/public/metadata)
SRCS(brand.proto)
END()
`)
	writeTestModuleFile(files, "ads/autobudget/protos/brand.proto", "syntax = \"proto3\";\npackage test;\nmessage Brand {}\n")

	writeTestModuleFile(files, consumer+"/ya.make", `PY3_LIBRARY()
NO_LIBC()
NO_RUNTIME()
NO_UTIL()
NO_PYTHON_INCLUDES()
PEERDIR(ads/autobudget/protos)
END()
`)
	writeTestModuleFile(files, "contrib/libs/protobuf/ya.make", "LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PLATFORM()\nSRCS(p.cpp)\nEND()\n")
	writeTestModuleFile(files, "contrib/python/protobuf/ya.make", "PY3_LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PYTHON_INCLUDES()\nEND()\n")
	writeTestModuleFile(files, "contrib/libs/python/ya.make", "LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PLATFORM()\nEND()\n")

	g := testGen(newMemFS(files), consumer)

	var pyPB *Node
	for _, n := range g.Graph {
		if n.KV.P == pkPB && n.TargetProperties.ModuleTag == tagPy3Proto &&
			strings.HasSuffix(n.Outputs[0].string(), "brand__intpy3___pb2.py") {
			pyPB = n
			break
		}
	}
	if pyPB == nil {
		t.Fatal("no python PB node for brand__intpy3___pb2.py emitted")
	}

	args := pyPB.Cmds[0].CmdArgs.flat()

	ytCount := 0
	for _, a := range args {
		if a.string() == "-I=$(S)/yt" {
			ytCount++
		}
	}
	if ytCount == 0 {
		t.Fatalf("py PB cmd missing transitive PROTO_NAMESPACE token -I=$(S)/yt: %v", strStrs(args))
	}
	if ytCount > 1 {
		t.Fatalf("py PB cmd duplicates -I=$(S)/yt (%d times): %v", ytCount, strStrs(args))
	}

	protobufSrcIdx := indexOfArg(args, "-I=$(S)/contrib/libs/protobuf/src")
	ytIdx := indexOfArg(args, "-I=$(S)/yt")
	protocSrcIdx := indexOfArg(args, "-I=$(S)/contrib/libs/protoc/src")
	pyOutIdx := indexOfArg(args, "--python_out=$(B)/")
	if protobufSrcIdx < 0 || pyOutIdx < 0 {
		t.Fatalf("py PB cmd missing protobuf-src / python_out anchors: %v", strStrs(args))
	}
	if !(protobufSrcIdx < ytIdx && ytIdx < pyOutIdx) {
		t.Fatalf("expected protobuf-src < yt < python_out: protobuf-src=%d yt=%d python_out=%d args=%v",
			protobufSrcIdx, ytIdx, pyOutIdx, strStrs(args))
	}
	if protocSrcIdx >= 0 && !(ytIdx < protocSrcIdx) {
		t.Fatalf("expected yt before protoc-src: yt=%d protoc-src=%d args=%v", ytIdx, protocSrcIdx, strStrs(args))
	}
}

// TestProtoPythonResourceKey_PYNamespacePreservesNestedSubdir pins the T-39B
// resource-key shape: with PY_NAMESPACE(yt_proto.yt.client) the aux resource key
// for a nested SRC must keep the module-local proto subdirectory under the
// namespace (yt_proto/yt/client/chunk_client/proto/data_statistics_pb2.py), not
// collapse it to filepath.Base (yt_proto/yt/client/data_statistics_pb2.py).
// Root-level SRCs (no subdir) are unaffected.
func TestProtoPythonResourceKey_PYNamespacePreservesNestedSubdir(t *testing.T) {
	instance := ModuleInstance{Path: source("yt/yt_proto/yt/client")}
	d := &ModuleData{pyNamespace: strPtr(internStr("yt_proto.yt.client"))}

	got := protoPythonResourceKey(instance, d, "chunk_client/proto/data_statistics.proto", "_pb2.py")
	const want = "yt_proto/yt/client/chunk_client/proto/data_statistics_pb2.py"
	if got != want {
		t.Errorf("nested PY_NAMESPACE key = %q, want %q", got, want)
	}

	const collapsed = "yt_proto/yt/client/data_statistics_pb2.py"
	if got == collapsed {
		t.Errorf("key collapsed nested subdir to %q", collapsed)
	}

	// Root-level source: no subdirectory to preserve, unchanged.
	gotRoot := protoPythonResourceKey(instance, d, "access_control_service.proto", "_pb2.py")
	const wantRoot = "yt_proto/yt/client/access_control_service_pb2.py"
	if gotRoot != wantRoot {
		t.Errorf("root-level PY_NAMESPACE key = %q, want %q", gotRoot, wantRoot)
	}
}

// pyProtoNamespaceIncludeCounts returns, for the py PB/grpc producer whose first
// output ends with wantSuffix, the total count of -I=$(S)/yt tokens and the
// flat command args. yt modules render -I=$(S)/yt three times: the
// -I=$ARCADIA_ROOT/$PROTO_NAMESPACE output-root arg plus two copies inside
// _PROTO__INCLUDE (the own namespace + the CPP_PROTO self-sibling re-contribution).
func pyProtoCmdArgsForOutput(t *testing.T, g *Graph, wantSuffix string) []STR {
	t.Helper()
	for _, n := range g.Graph {
		if n.KV.P == pkPB && n.TargetProperties.ModuleTag == tagPy3Proto &&
			len(n.Outputs) > 0 && strings.HasSuffix(n.Outputs[0].string(), wantSuffix) {
			return n.Cmds[0].CmdArgs.flat()
		}
	}
	t.Fatalf("no python PB node for %q", wantSuffix)
	return nil
}

func assertYtNamespaceDuplicated(t *testing.T, args []STR) {
	t.Helper()
	ytCount := 0
	for _, a := range args {
		if a.string() == "-I=$(S)/yt" {
			ytCount++
		}
	}
	if ytCount != 3 {
		t.Fatalf("expected 3 -I=$(S)/yt (output-root + duplicated _PROTO__INCLUDE), got %d: %v", ytCount, strStrs(args))
	}

	// Order: the two _PROTO__INCLUDE copies sit immediately after the bare
	// -I=$(S) and immediately before the protobuf-src include.
	bare := indexOfArg(args, "-I=$(S)")
	if bare < 0 || bare+3 >= len(args) {
		t.Fatalf("missing bare -I=$(S) anchor: %v", strStrs(args))
	}
	if args[bare+1].string() != "-I=$(S)/yt" || args[bare+2].string() != "-I=$(S)/yt" {
		t.Fatalf("expected two consecutive -I=$(S)/yt after -I=$(S): %v", strStrs(args))
	}
	if args[bare+3].string() != "-I=$(S)/contrib/libs/protobuf/src" {
		t.Fatalf("expected protobuf-src after the duplicated namespace: %v", strStrs(args))
	}
}

// TestGen_PyProtoLibrary_OwnPROTONamespaceDuplicatesNamespaceInclude reproduces
// the T-39B command gap: a PROTO_LIBRARY that declares its own PROTO_NAMESPACE(yt)
// (with PY_NAMESPACE) must render -I=$(S)/yt twice inside _PROTO__INCLUDE — the
// own namespace plus the CPP_PROTO self-sibling's GLOBAL re-contribution — exactly
// as the reference and the C++ duplicateOutputRootInclude path do. The aux
// resource key for the nested SRC must keep its module-local subdirectory.
func TestGen_PyProtoLibrary_OwnPROTONamespaceDuplicatesNamespaceInclude(t *testing.T) {
	const consumer = "app/pytool"
	const mod = "yt/yt_proto/yt/client"

	files := map[string]string{}
	writeToolProgram(files, "contrib/tools/protoc", "protoc")
	writeToolProgram(files, "contrib/tools/protoc/plugins/cpp_styleguide", "cpp_styleguide")
	writeToolProgram(files, "tools/py3cc", "py3cc")
	writeToolProgram(files, "tools/py3cc/slow", "py3cc_slow")
	writeToolProgram(files, "tools/rescompiler", "rescompiler")
	writeToolProgram(files, "contrib/python/mypy-protobuf/bin/protoc-gen-mypy", "protoc-gen-mypy")

	writeTestModuleFile(files, mod+"/ya.make", `PROTO_LIBRARY()
PROTO_NAMESPACE(yt)
PY_NAMESPACE(yt_proto.yt.client)
SRCS(chunk_client/proto/data_statistics.proto)
EXCLUDE_TAGS(GO_PROTO)
END()
`)
	writeTestModuleFile(files, mod+"/chunk_client/proto/data_statistics.proto", "syntax = \"proto3\";\npackage yt;\nmessage DataStatistics {}\n")

	writeTestModuleFile(files, consumer+"/ya.make", `PY3_LIBRARY()
NO_LIBC()
NO_RUNTIME()
NO_UTIL()
NO_PYTHON_INCLUDES()
PEERDIR(`+mod+`)
END()
`)
	writeTestModuleFile(files, "contrib/libs/protobuf/ya.make", "LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PLATFORM()\nSRCS(p.cpp)\nEND()\n")
	writeTestModuleFile(files, "contrib/python/protobuf/ya.make", "PY3_LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PYTHON_INCLUDES()\nEND()\n")
	writeTestModuleFile(files, "contrib/libs/python/ya.make", "LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PLATFORM()\nEND()\n")

	g := testGen(newMemFS(files), consumer)

	args := pyProtoCmdArgsForOutput(t, g, "data_statistics__intpy3___pb2.py")
	assertYtNamespaceDuplicated(t, args)

	// End-to-end: the aux/rescompiler resource key preserves the nested subdir.
	const wantKey = "resfs/file/py/yt_proto/yt/client/chunk_client/proto/data_statistics_pb2.py"
	const collapsedKey = "resfs/file/py/yt_proto/yt/client/data_statistics_pb2.py"
	foundKey, foundCollapsed := false, false
	for _, n := range g.Graph {
		if n.KV.P != pkPR {
			continue
		}
		for _, a := range n.Cmds[0].CmdArgs.flat() {
			s := a.string()
			if strings.Contains(s, wantKey) {
				foundKey = true
			}
			if strings.Contains(s, collapsedKey) {
				foundCollapsed = true
			}
		}
	}
	if !foundKey {
		t.Errorf("no aux resource key %q found", wantKey)
	}
	if foundCollapsed {
		t.Errorf("aux resource key still collapsed to %q", collapsedKey)
	}
}

// TestGen_PyProtoLibrary_GrpcRootSourceSharesDuplicateInclude covers the
// yt/orm/api shape: a GRPC root-level source keeps its existing _pb2_grpc.py
// output and its shared protoc producer carries the same duplicated -I=$(S)/yt.
func TestGen_PyProtoLibrary_GrpcRootSourceSharesDuplicateInclude(t *testing.T) {
	const consumer = "app/pytool"
	const mod = "yt/yt_proto/yt/orm/api"

	files := map[string]string{}
	writeToolProgram(files, "contrib/tools/protoc", "protoc")
	writeToolProgram(files, "contrib/tools/protoc/plugins/cpp_styleguide", "cpp_styleguide")
	writeToolProgram(files, "contrib/tools/protoc/plugins/grpc_cpp", "grpc_cpp")
	writeToolProgram(files, "contrib/tools/protoc/plugins/grpc_python", "grpc_python")
	writeToolProgram(files, "tools/py3cc", "py3cc")
	writeToolProgram(files, "tools/py3cc/slow", "py3cc_slow")
	writeToolProgram(files, "tools/rescompiler", "rescompiler")
	writeToolProgram(files, "contrib/python/mypy-protobuf/bin/protoc-gen-mypy", "protoc-gen-mypy")

	writeTestModuleFile(files, mod+"/ya.make", `PROTO_LIBRARY()
GRPC()
PROTO_NAMESPACE(yt)
PY_NAMESPACE(yt_proto.yt.orm.api)
SRCS(access_control_service.proto)
END()
`)
	writeTestModuleFile(files, mod+"/access_control_service.proto", "syntax = \"proto3\";\npackage yt;\nmessage Access {}\n")

	writeTestModuleFile(files, consumer+"/ya.make", `PY3_LIBRARY()
NO_LIBC()
NO_RUNTIME()
NO_UTIL()
NO_PYTHON_INCLUDES()
PEERDIR(`+mod+`)
END()
`)
	writeTestModuleFile(files, "contrib/libs/protobuf/ya.make", "LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PLATFORM()\nSRCS(p.cpp)\nEND()\n")
	writeTestModuleFile(files, "contrib/python/protobuf/ya.make", "PY3_LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PYTHON_INCLUDES()\nEND()\n")
	writeTestModuleFile(files, "contrib/python/grpcio/ya.make", "PY3_LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PYTHON_INCLUDES()\nEND()\n")
	writeTestModuleFile(files, "contrib/libs/grpc/ya.make", "LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PLATFORM()\nEND()\n")
	writeTestModuleFile(files, "contrib/libs/python/ya.make", "LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PLATFORM()\nEND()\n")

	g := testGen(newMemFS(files), consumer)

	// The grpc python output still exists and shares the PB producer command.
	args := pyProtoCmdArgsForOutput(t, g, "access_control_service__intpy3___pb2.py")
	assertYtNamespaceDuplicated(t, args)

	hasGrpcOut := false
	for _, n := range g.Graph {
		for _, o := range n.Outputs {
			if strings.HasSuffix(o.string(), "access_control_service__intpy3___pb2_grpc.py") {
				hasGrpcOut = true
			}
		}
	}
	if !hasGrpcOut {
		t.Fatal("grpc python output access_control_service__intpy3___pb2_grpc.py missing")
	}
}

// TestEmitProtoSrcs_CppEvlogCarriesEvent2cppInducedDeps reproduces the T-40
// residual: a PROTO_LIBRARY() with CPP_EVLOG() builds its .proto outputs as
// eventlog (upstream _BUILD_PROTO_AS_EVLOG), so tools/event2cpp is one of the
// protoc plugins producing the .pb.h/.pb.cc. event2cpp's INDUCED_DEPS(h+cpp …)
// must therefore reach the generated foo.pb.cc.o input closure — exactly as the
// true .ev path already does. An otherwise identical PROTO_LIBRARY() WITHOUT
// CPP_EVLOG() must NOT gain that induced input.
func TestEmitProtoSrcs_CppEvlogCarriesEvent2cppInducedDeps(t *testing.T) {
	files := map[string]string{}
	writeToolProgram(files, "contrib/tools/protoc", "protoc")
	writeToolProgram(files, "contrib/tools/protoc/plugins/cpp_styleguide", "cpp_styleguide")
	writeTestModuleFile(files, "build/scripts/cpp_proto_wrapper.py", "print('stub')\n")
	writeTestModuleFile(files, "contrib/libs/protobuf/ya.make", "LIBRARY()\nSRCS(protobuf.cpp)\nEND()\n")
	writeTestModuleFile(files, "contrib/libs/protobuf/protobuf.cpp", "int protobuf(){return 0;}\n")
	writeTestModuleFile(files, "library/cpp/eventlog/ya.make", "LIBRARY()\nSRCS(eventlog.cpp)\nEND()\n")
	writeTestModuleFile(files, "library/cpp/eventlog/eventlog.cpp", "int eventlog(){return 0;}\n")

	// Stub event2cpp tool declaring a single (h+cpp) induced header.
	writeTestModuleFile(files, "tools/event2cpp/ya.make",
		"PROGRAM(event2cpp)\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nINDUCED_DEPS(h+cpp ${ARCADIA_ROOT}/runtime/eventlog_runtime.h)\nSRCS(main.cpp)\nEND()\n")
	writeTestModuleFile(files, "tools/event2cpp/main.cpp", "int main(){return 0;}\n")
	writeTestModuleFile(files, "runtime/eventlog_runtime.h", "#pragma once\n")

	writeTestModuleFile(files, "evlog/ya.make",
		"PROTO_LIBRARY()\nSET(PROTOC_TRANSITIVE_HEADERS \"no\")\nCPP_EVLOG()\nSRCS(foo.proto)\nEND()\n")
	writeTestModuleFile(files, "evlog/foo.proto", "syntax = \"proto3\";\npackage test;\nmessage Foo { string v = 1; }\n")

	writeTestModuleFile(files, "plain/ya.make",
		"PROTO_LIBRARY()\nSET(PROTOC_TRANSITIVE_HEADERS \"no\")\nSRCS(foo.proto)\nEND()\n")
	writeTestModuleFile(files, "plain/foo.proto", "syntax = \"proto3\";\npackage test;\nmessage Foo { string v = 1; }\n")

	const induced = "$(S)/runtime/eventlog_runtime.h"

	gEv := testGen(newMemFS(files), "evlog")
	evCC := mustNodeByOutput(t, gEv, "$(B)/evlog/foo.pb.cc.o")
	if !nodeHasInput(evCC, induced) {
		t.Fatalf("CPP_EVLOG foo.pb.cc.o missing event2cpp induced input %q: %v", induced, evCC.flatInputs())
	}

	// T-58: CPP_EVLOG must also make event2cpp an ordinary C++ proto plugin on the
	// PB producer command — upstream CPP_PROTO_PLUGIN0(event2cpp tools/event2cpp …).
	pb := mustNodeByOutput(t, gEv, "$(B)/evlog/foo.pb.h")
	const event2cppBinary = "$(B)/tools/event2cpp/event2cpp"
	pbArgs := strStrs(pb.Cmds[0].CmdArgs.flat())
	const wantPlugin = "--plugin=protoc-gen-event2cpp=" + event2cppBinary
	const wantOut = "--event2cpp_out=$(B)/"
	if !containsString(pbArgs, wantPlugin) {
		t.Fatalf("CPP_EVLOG pb cmd missing event2cpp plugin token %q: %v", wantPlugin, pbArgs)
	}
	if !containsString(pbArgs, wantOut) {
		t.Fatalf("CPP_EVLOG pb cmd missing event2cpp out token %q: %v", wantOut, pbArgs)
	}
	srcIdx := indexOfArg(pb.Cmds[0].CmdArgs.flat(), "evlog/foo.proto")
	pluginIdx := indexOfArg(pb.Cmds[0].CmdArgs.flat(), wantPlugin)
	outIdx := indexOfArg(pb.Cmds[0].CmdArgs.flat(), wantOut)
	if srcIdx < 0 || pluginIdx < 0 || outIdx < 0 {
		t.Fatalf("CPP_EVLOG pb cmd missing src/plugin/out args: src=%d plugin=%d out=%d (%v)", srcIdx, pluginIdx, outIdx, pbArgs)
	}
	if !(srcIdx < pluginIdx && srcIdx < outIdx) {
		t.Fatalf("CPP_EVLOG pb plugin tokens must follow source: src=%d plugin=%d out=%d", srcIdx, pluginIdx, outIdx)
	}
	if !nodeHasInput(pb, event2cppBinary) {
		t.Fatalf("CPP_EVLOG pb producer missing event2cpp tool input %q: %v", event2cppBinary, pb.flatInputs())
	}
	event2cppNode := mustNodeByOutput(t, gEv, event2cppBinary)
	refs := 0
	for _, dep := range graphDeps(gEv, pb) {
		if dep == event2cppNode.UID {
			refs++
		}
	}
	if refs != 1 {
		t.Fatalf("CPP_EVLOG pb event2cpp generator ref count = %d, want 1 (no duplicate)", refs)
	}

	gPlain := testGen(newMemFS(files), "plain")
	plainCC := mustNodeByOutput(t, gPlain, "$(B)/plain/foo.pb.cc.o")
	if nodeHasInput(plainCC, induced) {
		t.Fatalf("non-CPP_EVLOG foo.pb.cc.o unexpectedly carries event2cpp induced input %q: %v", induced, plainCC.flatInputs())
	}
}

// T-54: a PROTO_LIBRARY leaf reached only through a peers list that was included
// via a variable-bearing INCLUDE path. Before parse-time expansion the peers
// list was skipped (its ${VAR} stayed literal), FEATURE_PEERDIRS expanded to
// nothing, and the leaf PY3 proto cluster never entered the graph. This mirrors
// the sg7 fs_codegen reachability class without real yabs files.
func TestParseInclude_VarBearingPeersListReachesLeafPyProto(t *testing.T) {
	const consumer = "app"

	files := map[string]string{}
	writeToolProgram(files, "contrib/tools/protoc", "protoc")
	writeToolProgram(files, "contrib/tools/protoc/plugins/cpp_styleguide", "cpp_styleguide")
	writeToolProgram(files, "tools/py3cc", "py3cc")
	writeToolProgram(files, "tools/py3cc/slow", "py3cc_slow")
	writeToolProgram(files, "tools/rescompiler", "rescompiler")

	writeTestModuleFile(files, consumer+"/ya.make", `PY3_LIBRARY(app)
NO_LIBC()
NO_RUNTIME()
NO_UTIL()
NO_PYTHON_INCLUDES()
INCLUDE(cfg/name.inc)
INCLUDE(${ARCADIA_ROOT}/gen/artefacts_${CONFIG_NAME}_/peers.lst)
PEERDIR(${FEATURE_PEERDIRS})
END()
`)
	writeTestModuleFile(files, consumer+"/cfg/name.inc", "SET(CONFIG_NAME caesar)\n")
	writeTestModuleFile(files, "gen/artefacts_caesar_/peers.lst", "SET(FEATURE_PEERDIRS feature/model)\n")
	writeTestModuleFile(files, "feature/model/ya.make", `PY3_LIBRARY()
NO_LIBC()
NO_RUNTIME()
NO_UTIL()
NO_PYTHON_INCLUDES()
PEERDIR(leaf/proto)
END()
`)
	writeTestModuleFile(files, "leaf/proto/ya.make", `PROTO_LIBRARY()
NO_MYPY()
SRCS(enum_options.proto)
EXCLUDE_TAGS(GO_PROTO JAVA_PROTO)
END()
`)
	writeTestModuleFile(files, "leaf/proto/enum_options.proto", "syntax = \"proto3\";\n")
	files["contrib/libs/protobuf/ya.make"] = "LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PLATFORM()\nSRCS(p.cpp)\nEND()\n"
	files["contrib/python/protobuf/ya.make"] = "PY3_LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PYTHON_INCLUDES()\nEND()\n"
	files["contrib/libs/python/ya.make"] = "LIBRARY()\nNO_LIBC()\nNO_RUNTIME()\nNO_UTIL()\nNO_PLATFORM()\nEND()\n"

	g := testGen(newMemFS(files), consumer)

	var pyPB *Node
	for _, n := range g.Graph {
		if n.KV.P == pkPB && n.TargetProperties.ModuleTag == tagPy3Proto &&
			len(n.Outputs) > 0 && strings.HasSuffix(n.Outputs[0].string(), "enum_options__intpy3___pb2.py") {
			pyPB = n
			break
		}
	}
	if pyPB == nil {
		t.Fatal("leaf PY3 proto enum_options__intpy3___pb2.py not reachable through variable-bearing include")
	}
}
