package main

// ENV name constants, pre-interned once at init (hoisted from per-call
// internEnv). Generated from the env-API call sites; keep in sync if new IF
// variable names are referenced.
var (
	envALLOCATOR                    = internEnv("ALLOCATOR")
	envAMX_CFLAGS                   = internEnv("AMX_CFLAGS")
	envANDROID_API                  = internEnv("ANDROID_API")
	envARCH_AARCH64                 = internEnv("ARCH_AARCH64")
	envARCH_ARM64                   = internEnv("ARCH_ARM64")
	envARCH_I386                    = internEnv("ARCH_I386")
	envARCH_X86_64                  = internEnv("ARCH_X86_64")
	envAVX2_CFLAGS                  = internEnv("AVX2_CFLAGS")
	envAVX512_CFLAGS                = internEnv("AVX512_CFLAGS")
	envAVX_CFLAGS                   = internEnv("AVX_CFLAGS")
	envBINDIR                       = internEnv("BINDIR")
	envBUILD_TYPE                   = internEnv("BUILD_TYPE")
	envCATBOOST_OPENSOURCE          = internEnv("CATBOOST_OPENSOURCE")
	envCLANG                        = internEnv("CLANG")
	envCLANG16_RESOURCE_GLOBAL      = internEnv("CLANG16_RESOURCE_GLOBAL")
	envCLANG18_RESOURCE_GLOBAL      = internEnv("CLANG18_RESOURCE_GLOBAL")
	envCLANG20_RESOURCE_GLOBAL      = internEnv("CLANG20_RESOURCE_GLOBAL")
	envCLANG_BC_ROOT                = internEnv("CLANG_BC_ROOT")
	envCOMPILER_VERSION             = internEnv("COMPILER_VERSION")
	envCURDIR                       = internEnv("CURDIR")
	envCX16_FLAGS                   = internEnv("CX16_FLAGS")
	envCXX_RT                       = internEnv("CXX_RT")
	envDISABLE_INSTRUCTION_SETS     = internEnv("DISABLE_INSTRUCTION_SETS")
	envGEN_PROTO                    = internEnv("GEN_PROTO")
	envLINUX                        = internEnv("LINUX")
	envLLVM_LLC_TOOL                = internEnv("LLVM_LLC_TOOL")
	envMODDIR                       = internEnv("MODDIR")
	envMODULE_TAG                   = internEnv("MODULE_TAG")
	envMUSL                         = internEnv("MUSL")
	envMUSL_LITE                    = internEnv("MUSL_LITE")
	envNO_STRIP                     = internEnv("NO_STRIP")
	envOPENSOURCE                   = internEnv("OPENSOURCE")
	envOPENSOURCE_PROJECT           = internEnv("OPENSOURCE_PROJECT")
	envORIG_SRC_DIR                 = internEnv("ORIG_SRC_DIR")
	envOS_LINUX                     = internEnv("OS_LINUX")
	envOS_SDK                       = internEnv("OS_SDK")
	envPOPCNT_CFLAGS                = internEnv("POPCNT_CFLAGS")
	envPROFILE_MEMORY_ALLOCATIONS   = internEnv("PROFILE_MEMORY_ALLOCATIONS")
	envPY2                          = internEnv("PY2")
	envPY3_PROTO                    = internEnv("PY3_PROTO")
	envPYTHON3                      = internEnv("PYTHON3")
	envSANITIZER_TYPE               = internEnv("SANITIZER_TYPE")
	envSRCDIR_RAW                   = internEnv("SRCDIR_RAW")
	envSSE41_CFLAGS                 = internEnv("SSE41_CFLAGS")
	envSSE42_CFLAGS                 = internEnv("SSE42_CFLAGS")
	envSSE4_CFLAGS                  = internEnv("SSE4_CFLAGS")
	envSSE_CFLAGS                   = internEnv("SSE_CFLAGS")
	envTRUE                         = internEnv("TRUE")
	envUSE_ARCADIA_COMPILER_RUNTIME = internEnv("USE_ARCADIA_COMPILER_RUNTIME")
	envUSE_ARCADIA_PYTHON           = internEnv("USE_ARCADIA_PYTHON")
	envUSE_SSE4                     = internEnv("USE_SSE4")
	envYA_OPENSOURCE                = internEnv("YA_OPENSOURCE")
	env_USE_ICONV                   = internEnv("_USE_ICONV")
	envaddress                      = internEnv("address")
	envleak                         = internEnv("leak")
	envmemory                       = internEnv("memory")
	envthread                       = internEnv("thread")
	envundefined                    = internEnv("undefined")
)
