// Code generated by dev/gen_parsers.py. DO NOT EDIT.
//
// The extension -> include-directive-parser dispatch: a per-length perfect
// hash over the registered extension set (the registrations live in the
// generator). One arithmetic hash, one slot read, one string compare.
package main

type extSlot struct {
	ext    string
	parser IncludeDirectiveParser
}

var extSlots = [120]extSlot{
	1:   {".y", CIncludeDirectiveParser{}},
	3:   {".l", CIncludeDirectiveParser{}},
	4:   {".m", CIncludeDirectiveParser{}},
	7:   {".C", CIncludeDirectiveParser{}},
	8:   {".S", CIncludeDirectiveParser{}},
	9:   {".c", CIncludeDirectiveParser{}},
	10:  {".s", CIncludeDirectiveParser{}},
	12:  {".H", CIncludeDirectiveParser{}},
	14:  {".h", CIncludeDirectiveParser{}},
	17:  {".go", CIncludeDirectiveParser{}},
	18:  {".g4", EmptyIncludeDirectiveParser{}},
	19:  {".mm", CIncludeDirectiveParser{}},
	20:  {".xh", CIncludeDirectiveParser{}},
	21:  {".hh", CIncludeDirectiveParser{}},
	22:  {".rl", RagelIncludeDirectiveParser{}},
	23:  {".cc", CIncludeDirectiveParser{}},
	24:  {".m4", EmptyIncludeDirectiveParser{}},
	25:  {".cu", CIncludeDirectiveParser{}},
	29:  {".ev", ProtoIncludeDirectiveParser{}},
	31:  {".rh", RagelIncludeDirectiveParser{}},
	32:  {".fbs", FlatbuffersIncludeDirectiveParser{}},
	34:  {".asi", YasmIncludeDirectiveParser{}},
	35:  {".pyx", CythonIncludeDirectiveParser{}},
	37:  {".stg", EmptyIncludeDirectiveParser{}},
	40:  {".swg", SwigIncludeDirectiveParser{}},
	41:  {".ypp", CIncludeDirectiveParser{}},
	44:  {".rli", RagelIncludeDirectiveParser{}},
	48:  {".rl5", RagelIncludeDirectiveParser{}},
	54:  {".pxi", CythonIncludeDirectiveParser{}},
	56:  {".rl6", RagelIncludeDirectiveParser{}},
	61:  {".inl", CIncludeDirectiveParser{}},
	65:  {".gzt", ProtoIncludeDirectiveParser{}},
	66:  {".asm", YasmIncludeDirectiveParser{}},
	81:  {".lex", CIncludeDirectiveParser{}},
	84:  {".pxd", CythonIncludeDirectiveParser{}},
	89:  {".cpp", CIncludeDirectiveParser{}},
	90:  {".asp", CIncludeDirectiveParser{}},
	91:  {".cxx", CIncludeDirectiveParser{}},
	94:  {".hpp", CIncludeDirectiveParser{}},
	95:  {".ipp", CIncludeDirectiveParser{}},
	96:  {".hxx", CIncludeDirectiveParser{}},
	97:  {".ixx", CIncludeDirectiveParser{}},
	98:  {".lpp", CIncludeDirectiveParser{}},
	100: {".cuh", CIncludeDirectiveParser{}},
	102: {".sfdl", CIncludeDirectiveParser{}},
	103: {".geom", CIncludeDirectiveParser{}},
	105: {".tesc", CIncludeDirectiveParser{}},
	106: {".comp", CIncludeDirectiveParser{}},
	107: {".tese", CIncludeDirectiveParser{}},
	109: {".frag", CIncludeDirectiveParser{}},
	110: {".vert", CIncludeDirectiveParser{}},
	114: {".proto", ProtoIncludeDirectiveParser{}},
	115: {".gperf", CIncludeDirectiveParser{}},
	116: {".auxcpp", CIncludeDirectiveParser{}},
	117: {".pxd.pxi", CythonIncludeDirectiveParser{}},
	118: {".pyx.pxi", CythonIncludeDirectiveParser{}},
	119: {".gztproto", ProtoIncludeDirectiveParser{}},
}

// lookupParserByExt returns the registered parser for an extension, or nil.
func lookupParserByExt(ext string) IncludeDirectiveParser {
	var i uint32

	switch len(ext) {
	case 2:
		i = (uint32(ext[1])) % 15
	case 3:
		i = 15 + (uint32(ext[1])+2*uint32(ext[2]))%17
	case 4:
		i = 32 + (uint32(ext[1])+uint32(ext[2])+8*uint32(ext[3]))%70
	case 5:
		i = 102 + (uint32(ext[4]))%12
	case 6:
		i = 114 + (uint32(ext[1]))%2
	case 7:
		i = 116
	case 8:
		i = 117 + (uint32(ext[2]))%2
	case 9:
		i = 119
	default:
		return nil
	}

	if extSlots[i].ext != ext {
		return nil
	}

	return extSlots[i].parser
}
