package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	goparser "go/parser"
	gotoken "go/token"
	"os"
	"sort"
	"strconv"
	"strings"
)

var goKeyword = map[string]bool{
	"break": true, "case": true, "chan": true, "const": true, "continue": true,
	"default": true, "defer": true, "else": true, "fallthrough": true, "for": true,
	"func": true, "go": true, "goto": true, "if": true, "import": true,
	"interface": true, "map": true, "package": true, "range": true, "return": true,
	"select": true, "struct": true, "switch": true, "type": true, "var": true,
}

var goPredeclared = map[string]bool{
	"any": true, "bool": true, "byte": true, "comparable": true,
	"complex64": true, "complex128": true, "error": true, "float32": true,
	"float64": true, "int": true, "int8": true, "int16": true, "int32": true,
	"int64": true, "rune": true, "string": true, "uint": true, "uint8": true,
	"uint16": true, "uint32": true, "uint64": true, "uintptr": true,
	"true": true, "false": true, "iota": true, "nil": true,
	"append": true, "cap": true, "clear": true, "close": true, "complex": true,
	"copy": true, "delete": true, "imag": true, "len": true, "make": true,
	"max": true, "min": true, "new": true, "panic": true, "print": true,
	"println": true, "real": true, "recover": true,
}

var linters = []FileLinter{
	{name: "strip-comments", run: lintStripComments},
	{name: "consolidate-vars", run: lintConsolidateVars},
	{name: "expand-func-bodies", run: lintExpandFuncBodies},
	{name: "func-blank-lines", run: lintFuncBlankLines},
	{name: "blank-around-blocks", run: lintControlBlankLines},
	{name: "tight-braces", run: lintTightBraces},
	{name: "case-convention", run: lintCaseConvention},
	{name: "coalesce-assign", run: lintCoalesceAssign},
}

var constFileForKind = map[HoistKind]string{
	hoistVFS: "vfs_consts.go",
	hoistStr: "str_consts.go",
	hoistArg: "arg_consts.go",
	hoistEnv: "env_consts.go",
}

var constFileHeader = map[HoistKind]string{
	hoistVFS: "// VFS path constants, interned once. Generated by `ay refac consts`.",
	hoistStr: "// STR constants, interned once. Generated by `ay refac consts`.",
	hoistArg: "// ARG (compiler/linker token) constants, interned once. Generated by `ay refac consts`.",
	hoistEnv: "// ENV name constants, interned once. Generated by `ay refac consts`.",
}

func isDefineAssign(s ast.Stmt) bool {
	as, ok := s.(*ast.AssignStmt)

	return ok && as.Tok == gotoken.DEFINE
}

func lintCoalesceAssign(path string) bool {
	src := throw2(os.ReadFile(path))
	fset := gotoken.NewFileSet()
	f, err := goparser.ParseFile(fset, path, src, goparser.ParseComments)

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac lint: %s: parse: %v\n", path, err)

		return false
	}

	lineOf := func(p gotoken.Pos) int { return fset.Position(p).Line }
	commentLine := map[int]bool{}

	for _, cg := range f.Comments {
		for _, c := range cg.List {
			for l := lineOf(c.Pos()); l <= lineOf(c.End()); l++ {
				commentLine[l] = true
			}
		}
	}

	lines := strings.Split(string(src), "\n")

	blank := func(l int) bool {
		return l >= 1 && l <= len(lines) && strings.TrimSpace(lines[l-1]) == ""
	}

	singleLine := func(s ast.Stmt) bool { return lineOf(s.Pos()) == lineOf(s.End()) }
	remove := map[int]bool{}

	process := func(list []ast.Stmt) {
		for i := 1; i < len(list); i++ {
			a, b := list[i-1], list[i]

			if !isDefineAssign(a) || !isDefineAssign(b) || !singleLine(a) || !singleLine(b) {
				continue
			}

			aEnd := lineOf(a.End())
			bStart := lineOf(b.Pos())
			allBlank := bStart > aEnd+1

			for l := aEnd + 1; l < bStart; l++ {
				if commentLine[l] || !blank(l) {
					allBlank = false

					break
				}
			}

			if allBlank {
				for l := aEnd + 1; l < bStart; l++ {
					remove[l] = true
				}
			}
		}
	}

	ast.Inspect(f, func(n ast.Node) bool {
		switch node := n.(type) {
		case *ast.BlockStmt:
			process(node.List)
		case *ast.CaseClause:
			process(node.Body)
		case *ast.CommClause:
			process(node.Body)
		}

		return true
	})

	if len(remove) == 0 {
		return false
	}

	var b strings.Builder

	for i, ln := range lines {
		if remove[i+1] {
			continue
		}

		b.WriteString(ln)

		if i < len(lines)-1 {
			b.WriteByte('\n')
		}
	}

	formatted, err := format.Source([]byte(b.String()))

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac lint: %s: coalesce-assign format failed (left unchanged): %v\n", path, err)

		return false
	}

	if bytes.Equal(formatted, src) {
		return false
	}

	throw(os.WriteFile(path, formatted, 0o644))

	return true
}

func goFilesFromArgs(args []string) []string {
	if len(args) > 0 {
		return args
	}

	var files []string

	for _, e := range throw2(os.ReadDir(".")) {
		n := e.Name()

		if !e.IsDir() && strings.HasSuffix(n, ".go") && !strings.HasSuffix(n, "_test.go") {
			files = append(files, n)
		}
	}

	sort.Strings(files)

	return files
}

func refacConsts(_ GlobalFlags, args []string) int {
	files := goFilesFromArgs(args)
	dest := map[string]bool{}

	for _, f := range constFileForKind {
		dest[f] = true
	}

	var parsed []*ParsedFile
	existing := map[HoistKey]string{}
	used := map[string]bool{}

	for _, path := range files {
		pf := parseRefacFile(path, existing, used)

		if pf != nil {
			parsed = append(parsed, pf)
		}
	}

	var occs []Occurrence

	for fi, pf := range parsed {
		collectOccurrences(pf, fi, &occs)
	}

	var emit []HoistedVar

	for _, pf := range parsed {
		emit = append(emit, pf.vars...)
	}

	for _, o := range occs {
		if !o.free {
			continue
		}

		if _, ok := existing[o.key]; ok {
			continue
		}

		name := uniqueName(identForVFS(o.key), used)
		used[name] = true
		existing[o.key] = name
		emit = append(emit, HoistedVar{name, o.key})
	}

	editsByFile := make([][]ConstEdit, len(parsed))

	for _, o := range occs {
		name, ok := existing[o.key]

		if !ok {
			continue
		}

		editsByFile[o.fileIdx] = append(editsByFile[o.fileIdx], ConstEdit{o.start, o.end, name})
	}

	for fi, pf := range parsed {
		if dest[pf.path] {
			continue
		}

		editsByFile[fi] = append(editsByFile[fi], removalEdits(pf)...)
		editsByFile[fi] = append(editsByFile[fi], internArgsRewrites(pf, existing, used, &emit)...)

		if applyConstEdits(pf, editsByFile[fi]) {
			fmt.Fprintf(os.Stderr, "refac consts: rewrote %s\n", pf.path)
		}
	}

	for kind, fname := range constFileForKind {
		generateConstFile(fname, kind, emit)
	}

	return 0
}

type Occurrence struct {
	fileIdx    int
	start, end int
	key        HoistKey
	free       bool
}

func collectOccurrences(pf *ParsedFile, fileIdx int, occs *[]Occurrence) {
	record := func(call *ast.CallExpr, free bool) bool {
		if pf.declared[call] {
			return false
		}

		key, ok := hoistCall(call)

		if !ok {
			return true
		}

		*occs = append(*occs, Occurrence{
			fileIdx: fileIdx,
			start:   pf.fset.Position(call.Pos()).Offset,
			end:     pf.fset.Position(call.End()).Offset,
			key:     key,
			free:    free,
		})

		return false
	}

	for _, decl := range pf.f.Decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			ast.Inspect(d, func(n ast.Node) bool {
				if call, ok := n.(*ast.CallExpr); ok {
					return record(call, true)
				}

				return true
			})
		case *ast.GenDecl:
			if d.Tok != gotoken.VAR && d.Tok != gotoken.CONST {
				continue
			}

			for _, spec := range d.Specs {
				vs, ok := spec.(*ast.ValueSpec)

				if !ok {
					continue
				}

				for _, val := range vs.Values {
					ast.Inspect(val, func(n ast.Node) bool {
						if call, ok := n.(*ast.CallExpr); ok {
							return record(call, false)
						}

						return true
					})
				}
			}
		}
	}
}

type ParsedFile struct {
	path     string
	src      []byte
	fset     *gotoken.FileSet
	f        *ast.File
	declared map[*ast.CallExpr]bool
	vars     []HoistedVar
}

type HoistedVar struct {
	name string
	key  HoistKey
}

func parseRefacFile(path string, existing map[HoistKey]string, used map[string]bool) *ParsedFile {
	src := throw2(os.ReadFile(path))
	fset := gotoken.NewFileSet()
	f, err := goparser.ParseFile(fset, path, src, goparser.ParseComments)

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac consts: %s: parse: %v\n", path, err)

		return nil
	}

	declared := map[*ast.CallExpr]bool{}
	var vars []HoistedVar

	for _, decl := range f.Decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			used[d.Name.Name] = true
		case *ast.GenDecl:
			for _, spec := range d.Specs {
				switch s := spec.(type) {
				case *ast.TypeSpec:
					used[s.Name.Name] = true
				case *ast.ValueSpec:
					for _, n := range s.Names {
						used[n.Name] = true
					}

					if d.Tok == gotoken.VAR || d.Tok == gotoken.CONST {
						for i, val := range s.Values {
							call, isCall := val.(*ast.CallExpr)

							if !isCall || i >= len(s.Names) {
								continue
							}

							if key, ok := hoistCall(call); ok {
								if _, seen := existing[key]; !seen {
									existing[key] = s.Names[i].Name
								}

								declared[call] = true
								vars = append(vars, HoistedVar{s.Names[i].Name, key})
							}
						}
					}
				}
			}
		}
	}

	return &ParsedFile{path: path, src: src, fset: fset, f: f, declared: declared, vars: vars}
}

type HoistKind uint8

const (
	hoistVFS HoistKind = iota
	hoistStr
	hoistArg
	hoistEnv
)

type HoistKey struct {
	kind  HoistKind
	canon string
}

func hoistCall(call *ast.CallExpr) (HoistKey, bool) {
	id, isID := call.Fun.(*ast.Ident)

	if !isID {
		return HoistKey{}, false
	}

	if len(call.Args) != 1 {
		return HoistKey{}, false
	}

	bl, isLit := call.Args[0].(*ast.BasicLit)

	if !isLit || bl.Kind != gotoken.STRING {
		return HoistKey{}, false
	}

	lit, err := strconv.Unquote(bl.Value)

	if err != nil {
		return HoistKey{}, false
	}

	switch id.Name {
	case "intern":
		return HoistKey{kind: hoistVFS, canon: lit}, true
	case "source":
		return HoistKey{kind: hoistVFS, canon: "$(S)/" + lit}, true
	case "build":
		return HoistKey{kind: hoistVFS, canon: "$(B)/" + lit}, true
	case "internStr":
		return HoistKey{kind: hoistStr, canon: lit}, true
	case "internArg":
		return HoistKey{kind: hoistArg, canon: lit}, true
	case "internEnv":
		return HoistKey{kind: hoistEnv, canon: lit}, true
	}

	return HoistKey{}, false
}

func constDef(key HoistKey) string {
	switch key.kind {
	case hoistStr:
		return fmt.Sprintf("internStr(%q)", key.canon)
	case hoistArg:
		return fmt.Sprintf("internArg(%q)", key.canon)
	case hoistEnv:
		return fmt.Sprintf("internEnv(%q)", key.canon)
	}

	if rel, ok := strings.CutPrefix(key.canon, "$(S)/"); ok {
		return fmt.Sprintf("source(%q)", rel)
	}

	if rel, ok := strings.CutPrefix(key.canon, "$(B)/"); ok {
		return fmt.Sprintf("build(%q)", rel)
	}

	return fmt.Sprintf("intern(%q)", key.canon)
}

type ConstEdit struct {
	start, end int
	name       string
}

func internArgsRewrites(pf *ParsedFile, existing map[HoistKey]string, used map[string]bool, emit *[]HoistedVar) []ConstEdit {
	off := func(p gotoken.Pos) int { return pf.fset.Position(p).Offset }

	var edits []ConstEdit

	ast.Inspect(pf.f, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)

		if !ok {
			return true
		}

		id, isID := call.Fun.(*ast.Ident)

		if !isID || id.Name != "internArgs" || len(call.Args) != 1 {
			return true
		}

		cl, isComposite := call.Args[0].(*ast.CompositeLit)

		if !isComposite || len(cl.Elts) == 0 {
			return true
		}

		names := make([]string, 0, len(cl.Elts))

		for _, el := range cl.Elts {
			bl, isLit := el.(*ast.BasicLit)

			if !isLit || bl.Kind != gotoken.STRING {
				return true
			}

			lit, err := strconv.Unquote(bl.Value)

			if err != nil {
				return true
			}

			key := HoistKey{kind: hoistArg, canon: lit}
			name, seen := existing[key]

			if !seen {
				name = uniqueName(identForVFS(key), used)
				used[name] = true
				existing[key] = name
				*emit = append(*emit, HoistedVar{name, key})
			}

			names = append(names, name)
		}

		var b strings.Builder
		b.WriteString("[]ARG{")

		for _, nm := range names {
			b.WriteByte('\n')
			b.WriteString(nm)
			b.WriteByte(',')
		}

		b.WriteString("\n}")
		edits = append(edits, ConstEdit{off(call.Pos()), off(call.End()), b.String()})

		return false
	})

	return edits
}

func specRemovable(pf *ParsedFile, spec ast.Spec) bool {
	vs, ok := spec.(*ast.ValueSpec)

	if !ok || len(vs.Names) != 1 || len(vs.Values) != 1 {
		return false
	}

	call, ok := vs.Values[0].(*ast.CallExpr)

	return ok && pf.declared[call]
}

func removalEdits(pf *ParsedFile) []ConstEdit {
	src := pf.src
	off := func(p gotoken.Pos) int { return pf.fset.Position(p).Offset }

	lineStart := func(o int) int {
		for o > 0 && src[o-1] != '\n' {
			o--
		}

		return o
	}

	lineEndIncl := func(o int) int {
		for o < len(src) && src[o] != '\n' {
			o++
		}

		if o < len(src) {
			o++
		}

		return o
	}

	var edits []ConstEdit

	for _, decl := range pf.f.Decls {
		gd, ok := decl.(*ast.GenDecl)

		if !ok || gd.Tok != gotoken.VAR {
			continue
		}

		removable := 0

		for _, spec := range gd.Specs {
			if specRemovable(pf, spec) {
				removable++
			}
		}

		if removable == 0 {
			continue
		}

		if removable == len(gd.Specs) {
			start := gd.Pos()

			if gd.Doc != nil {
				start = gd.Doc.Pos()
			}

			edits = append(edits, ConstEdit{lineStart(off(start)), lineEndIncl(off(gd.End()) - 1), ""})

			continue
		}

		for _, spec := range gd.Specs {
			if !specRemovable(pf, spec) {
				continue
			}

			vs := spec.(*ast.ValueSpec)
			start := vs.Pos()

			if vs.Doc != nil {
				start = vs.Doc.Pos()
			}

			end := vs.End()

			if vs.Comment != nil {
				end = vs.Comment.End()
			}

			edits = append(edits, ConstEdit{lineStart(off(start)), lineEndIncl(off(end) - 1), ""})
		}
	}

	return edits
}

func applyConstEdits(pf *ParsedFile, edits []ConstEdit) bool {
	if len(edits) == 0 {
		return false
	}

	sort.Slice(edits, func(i, j int) bool { return edits[i].start > edits[j].start })
	out := append([]byte(nil), pf.src...)

	for _, e := range edits {
		out = append(out[:e.start], append([]byte(e.name), out[e.end:]...)...)
	}

	formatted, err := format.Source(out)

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac consts: %s: format failed (left unchanged): %v\n", pf.path, err)

		return false
	}

	if bytes.Equal(formatted, pf.src) {
		return false
	}

	throw(os.WriteFile(pf.path, formatted, 0o644))

	return true
}

func generateConstFile(path string, kind HoistKind, vars []HoistedVar) {
	var items []HoistedVar
	seen := map[string]bool{}

	for _, v := range vars {
		if v.key.kind != kind || seen[v.name] {
			continue
		}

		seen[v.name] = true
		items = append(items, v)
	}

	if len(items) == 0 {
		if _, err := os.Stat(path); err == nil {
			throw(os.Remove(path))
			fmt.Fprintf(os.Stderr, "refac consts: removed empty %s\n", path)
		}

		return
	}

	sort.Slice(items, func(i, j int) bool { return items[i].name < items[j].name })

	var b strings.Builder
	b.WriteString("package main\n\n")
	b.WriteString(constFileHeader[kind])
	b.WriteString("\nvar (\n")

	for _, it := range items {
		fmt.Fprintf(&b, "\t%s = %s\n", it.name, constDef(it.key))
	}

	b.WriteString(")\n")
	formatted := throw2(format.Source([]byte(b.String())))
	throw(os.WriteFile(path, formatted, 0o644))
	fmt.Fprintf(os.Stderr, "refac consts: generated %s (%d consts)\n", path, len(items))
}

func identForVFS(key HoistKey) string {
	s := key.canon
	var words []string

	switch {
	case key.kind == hoistStr:
		words = append(words, "str")
	case key.kind == hoistArg:
		words = append(words, "arg")
	case key.kind == hoistEnv:
		words = append(words, "env")
	default:
		if rel, ok := strings.CutPrefix(s, "$(S)/"); ok {
			s = rel
		} else if rel, ok := strings.CutPrefix(s, "$(B)/"); ok {
			s = rel
			words = append(words, "bld")
		}
	}

	var cur strings.Builder

	flush := func() {
		if cur.Len() > 0 {
			words = append(words, cur.String())
			cur.Reset()
		}
	}

	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			cur.WriteRune(r)
		} else {
			flush()
		}
	}

	flush()

	if len(words) == 0 {
		words = []string{"v"}
	}

	var b strings.Builder

	for i, w := range words {
		w = strings.ToLower(w)

		if i == 0 {
			b.WriteString(w)
		} else {
			b.WriteString(strings.ToUpper(w[:1]) + w[1:])
		}
	}

	id := b.String()

	if c := id[0]; c >= '0' && c <= '9' {
		id = "v" + id
	}

	return id
}

func uniqueName(base string, used map[string]bool) string {
	if !used[base] && !goKeyword[base] && !goPredeclared[base] {
		return base
	}

	for i := 2; ; i++ {
		cand := base + strconv.Itoa(i)

		if !used[cand] {
			return cand
		}
	}
}

type FileLinter struct {
	name string
	run  func(path string) bool
}

func commentIsDirective(text string) bool {
	t := strings.TrimSpace(text)

	return strings.HasPrefix(t, "//go:") ||
		strings.HasPrefix(t, "// +build") ||
		strings.HasPrefix(t, "//line ") ||
		strings.HasPrefix(t, "//extern")
}

func lintStripComments(path string) bool {
	src := throw2(os.ReadFile(path))
	fset := gotoken.NewFileSet()
	f, err := goparser.ParseFile(fset, path, src, goparser.ParseComments)

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac lint: %s: parse: %v\n", path, err)

		return false
	}

	kept := f.Comments[:0]
	changed := false

	for _, g := range f.Comments {
		dir := g.List[:0]

		for _, c := range g.List {
			if commentIsDirective(c.Text) {
				dir = append(dir, c)
			}
		}

		if len(dir) != len(g.List) {
			changed = true
		}

		if len(dir) > 0 {
			g.List = dir
			kept = append(kept, g)
		}
	}

	if !changed {
		return false
	}

	f.Comments = kept
	f.Doc = nil

	var buf bytes.Buffer

	if err := format.Node(&buf, fset, f); err != nil {
		fmt.Fprintf(os.Stderr, "refac lint: %s: strip-comments format failed (left unchanged): %v\n", path, err)

		return false
	}

	formatted, err := format.Source(buf.Bytes())

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac lint: %s: strip-comments reformat failed (left unchanged): %v\n", path, err)

		return false
	}

	if bytes.Equal(formatted, src) {
		return false
	}

	throw(os.WriteFile(path, formatted, 0o644))

	return true
}

func refacLint(_ GlobalFlags, args []string) int {
	files := goFilesFromArgs(args)

	for _, path := range files {
		for _, l := range linters {
			if l.run(path) {
				fmt.Fprintf(os.Stderr, "refac lint: %s: %s\n", l.name, path)
			}
		}
	}

	return 0
}

type VarItem struct {
	blockDoc  string
	doc       string
	body      string
	multiline bool
}

func (it VarItem) render(inGroup bool) string {
	var b strings.Builder

	if it.blockDoc != "" {
		b.WriteString(it.blockDoc)
		b.WriteByte('\n')
	}

	if it.doc != "" {
		b.WriteString(it.doc)
		b.WriteByte('\n')
	}

	if !inGroup {
		b.WriteString("var ")
	}

	b.WriteString(it.body)

	return b.String()
}

func lintConsolidateVars(path string) bool {
	src := throw2(os.ReadFile(path))
	fset := gotoken.NewFileSet()
	f, err := goparser.ParseFile(fset, path, src, goparser.ParseComments)

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac lint: %s: parse: %v\n", path, err)

		return false
	}

	var varDecls []*ast.GenDecl
	totalSpecs := 0

	for _, decl := range f.Decls {
		if gd, ok := decl.(*ast.GenDecl); ok && gd.Tok == gotoken.VAR {
			varDecls = append(varDecls, gd)
			totalSpecs += len(gd.Specs)
		}
	}

	if totalSpecs < 2 {
		return false
	}

	off := func(p gotoken.Pos) int { return fset.Position(p).Offset }
	text := func(lo, hi gotoken.Pos) string { return string(src[off(lo):off(hi)]) }
	type span struct{ start, end int }
	var items []VarItem
	var removals []span

	for _, gd := range varDecls {
		rmStart := off(gd.Pos())

		if gd.Doc != nil {
			rmStart = off(gd.Doc.Pos())
		}

		rmEnd := off(gd.End())
		blockDoc := ""

		if gd.Lparen.IsValid() && gd.Doc != nil {
			blockDoc = text(gd.Doc.Pos(), gd.Doc.End())
		}

		for _, spec := range gd.Specs {
			vs := spec.(*ast.ValueSpec)
			hi := vs.End()

			if vs.Comment != nil {
				hi = vs.Comment.End()

				if off(hi) > rmEnd {
					rmEnd = off(hi)
				}
			}

			doc := ""

			if vs.Doc != nil {
				doc = text(vs.Doc.Pos(), vs.Doc.End())
			} else if !gd.Lparen.IsValid() && gd.Doc != nil {
				doc = text(gd.Doc.Pos(), gd.Doc.End())
			}

			items = append(items, VarItem{
				blockDoc:  blockDoc,
				doc:       doc,
				body:      text(vs.Pos(), hi),
				multiline: strings.IndexByte(text(vs.Pos(), vs.End()), '\n') >= 0,
			})
			blockDoc = ""
		}

		removals = append(removals, span{rmStart, rmEnd})
	}

	simpleCount := 0

	for _, it := range items {
		if !it.multiline {
			simpleCount++
		}
	}

	group := simpleCount >= 2

	var parts []string

	if group {
		var b strings.Builder
		b.WriteString("var (\n")

		for _, it := range items {
			if it.multiline {
				continue
			}

			b.WriteString(it.render(true))
			b.WriteByte('\n')
		}

		b.WriteString(")")
		parts = append(parts, b.String())

		for _, it := range items {
			if it.multiline {
				parts = append(parts, it.render(false))
			}
		}
	} else {
		for _, it := range items {
			parts = append(parts, it.render(false))
		}
	}

	insOff := off(f.Name.End())

	for _, decl := range f.Decls {
		if gd, ok := decl.(*ast.GenDecl); ok && gd.Tok == gotoken.IMPORT {
			insOff = off(gd.End())

			break
		}
	}

	out := append([]byte(nil), src...)
	sort.Slice(removals, func(i, j int) bool { return removals[i].start > removals[j].start })

	for _, r := range removals {
		out = append(out[:r.start], out[r.end:]...)
	}

	block := "\n\n" + strings.Join(parts, "\n\n") + "\n"
	out = append(out[:insOff], append([]byte(block), out[insOff:]...)...)

	formatted, err := format.Source(out)

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac lint: %s: consolidate-vars format failed (left unchanged): %v\n", path, err)

		return false
	}

	if bytes.Equal(formatted, src) {
		return false
	}

	throw(os.WriteFile(path, formatted, 0o644))

	return true
}

func isControlBlockStmt(stmt ast.Stmt) bool {
	switch s := stmt.(type) {
	case *ast.IfStmt, *ast.ForStmt, *ast.RangeStmt, *ast.SwitchStmt, *ast.TypeSwitchStmt, *ast.SelectStmt:
		return true
	case *ast.ReturnStmt, *ast.DeferStmt:
		return true
	case *ast.BranchStmt:
		return s.Tok == gotoken.BREAK || s.Tok == gotoken.CONTINUE
	case *ast.GoStmt:
		_, ok := s.Call.Fun.(*ast.FuncLit)

		return ok
	case *ast.LabeledStmt:
		return isControlBlockStmt(s.Stmt)
	}

	return false
}

func lintControlBlankLines(path string) bool {
	src := throw2(os.ReadFile(path))
	fset := gotoken.NewFileSet()
	f, err := goparser.ParseFile(fset, path, src, goparser.ParseComments)

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac lint: %s: parse: %v\n", path, err)

		return false
	}

	lineOf := func(p gotoken.Pos) int { return fset.Position(p).Line }
	commentLine := map[int]bool{}

	for _, cg := range f.Comments {
		for _, c := range cg.List {
			for l := lineOf(c.Pos()); l <= lineOf(c.End()); l++ {
				commentLine[l] = true
			}
		}
	}

	insertBefore := map[int]bool{}

	blockLike := func(s ast.Stmt) bool {
		return isControlBlockStmt(s) || (isDefineAssign(s) && lineOf(s.End()) > lineOf(s.Pos()))
	}

	process := func(list []ast.Stmt) {
		for i := 1; i < len(list); i++ {
			a, b := list[i-1], list[i]

			if !blockLike(a) && !blockLike(b) {
				continue
			}

			aEnd := lineOf(a.End())
			lead := lineOf(b.Pos())

			for l := lead - 1; l > aEnd && commentLine[l]; l-- {
				lead = l
			}

			if lead == aEnd+1 {
				insertBefore[lead] = true
			}
		}
	}

	ast.Inspect(f, func(n ast.Node) bool {
		switch node := n.(type) {
		case *ast.BlockStmt:
			process(node.List)
		case *ast.CaseClause:
			process(node.Body)
		case *ast.CommClause:
			process(node.Body)
		}

		return true
	})

	if len(insertBefore) == 0 {
		return false
	}

	lines := strings.Split(string(src), "\n")
	var b strings.Builder

	for i, ln := range lines {
		if insertBefore[i+1] {
			b.WriteByte('\n')
		}

		b.WriteString(ln)

		if i < len(lines)-1 {
			b.WriteByte('\n')
		}
	}

	formatted, err := format.Source([]byte(b.String()))

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac lint: %s: blank-around-blocks format failed (left unchanged): %v\n", path, err)

		return false
	}

	if bytes.Equal(formatted, src) {
		return false
	}

	throw(os.WriteFile(path, formatted, 0o644))

	return true
}

func lintTightBraces(path string) bool {
	src := throw2(os.ReadFile(path))
	fset := gotoken.NewFileSet()
	f, err := goparser.ParseFile(fset, path, src, goparser.ParseComments)

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac lint: %s: parse: %v\n", path, err)

		return false
	}

	lineOf := func(p gotoken.Pos) int { return fset.Position(p).Line }
	lines := strings.Split(string(src), "\n")

	isBlank := func(l int) bool {
		return l >= 1 && l <= len(lines) && strings.TrimSpace(lines[l-1]) == ""
	}

	del := map[int]bool{}

	tighten := func(open, close gotoken.Pos) {
		if !open.IsValid() || !close.IsValid() {
			return
		}

		openLine, closeLine := lineOf(open), lineOf(close)

		for l := openLine + 1; l < closeLine && isBlank(l); l++ {
			del[l] = true
		}

		for l := closeLine - 1; l > openLine && isBlank(l); l-- {
			del[l] = true
		}
	}

	ast.Inspect(f, func(n ast.Node) bool {
		switch x := n.(type) {
		case *ast.BlockStmt:
			tighten(x.Lbrace, x.Rbrace)
		case *ast.CompositeLit:
			tighten(x.Lbrace, x.Rbrace)
		case *ast.StructType:
			if x.Fields != nil {
				tighten(x.Fields.Opening, x.Fields.Closing)
			}
		case *ast.InterfaceType:
			if x.Methods != nil {
				tighten(x.Methods.Opening, x.Methods.Closing)
			}
		}

		return true
	})

	if len(del) == 0 {
		return false
	}

	kept := make([]string, 0, len(lines))

	for i, ln := range lines {
		if del[i+1] {
			continue
		}

		kept = append(kept, ln)
	}

	formatted, err := format.Source([]byte(strings.Join(kept, "\n")))

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac lint: %s: tight-braces format failed (left unchanged): %v\n", path, err)

		return false
	}

	if bytes.Equal(formatted, src) {
		return false
	}

	throw(os.WriteFile(path, formatted, 0o644))

	return true
}

func lintExpandFuncBodies(path string) bool {
	src := throw2(os.ReadFile(path))
	fset := gotoken.NewFileSet()
	f, err := goparser.ParseFile(fset, path, src, goparser.ParseComments)

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac lint: %s: parse: %v\n", path, err)

		return false
	}

	lineOf := func(p gotoken.Pos) int { return fset.Position(p).Line }
	offOf := func(p gotoken.Pos) int { return fset.Position(p).Offset }

	var offs []int

	for _, d := range f.Decls {
		fn, ok := d.(*ast.FuncDecl)

		if !ok || fn.Body == nil {
			continue
		}

		if lineOf(fn.Body.Lbrace) != lineOf(fn.Body.Rbrace) {
			continue
		}

		if len(fn.Body.List) == 0 {
			offs = append(offs, offOf(fn.Body.Rbrace))

			continue
		}

		offs = append(offs, offOf(fn.Body.Lbrace)+1, offOf(fn.Body.Rbrace))
	}

	if len(offs) == 0 {
		return false
	}

	sort.Sort(sort.Reverse(sort.IntSlice(offs)))
	b := src

	for _, off := range offs {
		b = append(b[:off:off], append([]byte("\n"), b[off:]...)...)
	}

	formatted, err := format.Source(b)

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac lint: %s: expand-func-bodies format failed (left unchanged): %v\n", path, err)

		return false
	}

	if bytes.Equal(formatted, src) {
		return false
	}

	throw(os.WriteFile(path, formatted, 0o644))

	return true
}

func lintFuncBlankLines(path string) bool {
	src := throw2(os.ReadFile(path))
	fset := gotoken.NewFileSet()
	f, err := goparser.ParseFile(fset, path, src, goparser.ParseComments)

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac lint: %s: parse: %v\n", path, err)

		return false
	}

	lineOf := func(p gotoken.Pos) int { return fset.Position(p).Line }
	lines := strings.Split(string(src), "\n")

	isBlank := func(l int) bool {
		return l >= 1 && l <= len(lines) && strings.TrimSpace(lines[l-1]) == ""
	}

	insertBefore := map[int]bool{}

	for _, d := range f.Decls {
		fn, ok := d.(*ast.FuncDecl)

		if !ok {
			continue
		}

		top := lineOf(fn.Pos())

		if fn.Doc != nil {
			top = lineOf(fn.Doc.Pos())
		}

		if top > 1 && !isBlank(top-1) {
			insertBefore[top] = true
		}

		end := lineOf(fn.End())

		if end+1 <= len(lines) && !isBlank(end+1) {
			insertBefore[end+1] = true
		}
	}

	if len(insertBefore) == 0 {
		return false
	}

	var b strings.Builder

	for i, ln := range lines {
		if insertBefore[i+1] {
			b.WriteByte('\n')
		}

		b.WriteString(ln)

		if i < len(lines)-1 {
			b.WriteByte('\n')
		}
	}

	formatted, err := format.Source([]byte(b.String()))

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac lint: %s: func-blank-lines format failed (left unchanged): %v\n", path, err)

		return false
	}

	if bytes.Equal(formatted, src) {
		return false
	}

	throw(os.WriteFile(path, formatted, 0o644))

	return true
}
