package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	goparser "go/parser"
	gotoken "go/token"
	"os"
	"sort"
	"strconv"
	"strings"
)

var goKeyword = map[string]bool{
	"break": true, "case": true, "chan": true, "const": true, "continue": true,
	"default": true, "defer": true, "else": true, "fallthrough": true, "for": true,
	"func": true, "go": true, "goto": true, "if": true, "import": true,
	"interface": true, "map": true, "package": true, "range": true, "return": true,
	"select": true, "struct": true, "switch": true, "type": true, "var": true,
}

// goPredeclared lists Go's predeclared identifiers: not keywords, but reserved so
// uniqueName never emits a name that shadows a builtin.
var goPredeclared = map[string]bool{
	"any": true, "bool": true, "byte": true, "comparable": true,
	"complex64": true, "complex128": true, "error": true, "float32": true,
	"float64": true, "int": true, "int8": true, "int16": true, "int32": true,
	"int64": true, "rune": true, "string": true, "uint": true, "uint8": true,
	"uint16": true, "uint32": true, "uint64": true, "uintptr": true,
	"true": true, "false": true, "iota": true, "nil": true,
	"append": true, "cap": true, "clear": true, "close": true, "complex": true,
	"copy": true, "delete": true, "imag": true, "len": true, "make": true,
	"max": true, "min": true, "new": true, "panic": true, "print": true,
	"println": true, "real": true, "recover": true,
}

// linters is the fixed set applied by `ay refac lint`.
var linters = []FileLinter{
	{name: "consolidate-vars", run: lintConsolidateVars},
	{name: "expand-func-bodies", run: lintExpandFuncBodies},
	{name: "func-blank-lines", run: lintFuncBlankLines},
	{name: "blank-around-blocks", run: lintControlBlankLines},
	{name: "tight-braces", run: lintTightBraces},
	{name: "case-convention", run: lintCaseConvention},
}

// constFileForKind names the dedicated file owning every hoisted const of a kind.
// `ay refac consts` regenerates these files wholesale.
var constFileForKind = map[HoistKind]string{
	hoistVFS: "vfs_consts.go",
	hoistStr: "str_consts.go",
	hoistArg: "arg_consts.go",
	hoistEnv: "env_consts.go",
}

var constFileHeader = map[HoistKind]string{
	hoistVFS: "// VFS path constants, interned once. Generated by `ay refac consts`.",
	hoistStr: "// STR constants, interned once. Generated by `ay refac consts`.",
	hoistArg: "// ARG (compiler/linker token) constants, interned once. Generated by `ay refac consts`.",
	hoistEnv: "// ENV name constants, interned once. Generated by `ay refac consts`.",
}

// In-tree refactoring helpers mutate source files in place; run them in a
// throwaway worktree and review the diff.

// goFilesFromArgs returns the explicit file args, or every non-test .go file in
// the current dir, sorted.
func goFilesFromArgs(args []string) []string {
	if len(args) > 0 {
		return args
	}

	var files []string

	for _, e := range throw2(os.ReadDir(".")) {
		n := e.Name()

		if !e.IsDir() && strings.HasSuffix(n, ".go") && !strings.HasSuffix(n, "_test.go") {
			files = append(files, n)
		}
	}

	sort.Strings(files)

	return files
}

// refacConsts hoists every intern/source/build call with a constant string literal
// out of function bodies into a package-level var, deduped by resolved VFS path.
// Dedup and name allocation are package-wide, so a VFS hoisted in one file is
// referenced when it recurs in another.
func refacConsts(_ GlobalFlags, args []string) int {
	files := goFilesFromArgs(args)

	dest := map[string]bool{}

	for _, f := range constFileForKind {
		dest[f] = true
	}

	// Phase 1: parse every file and collect package-wide state.
	var parsed []*ParsedFile
	existing := map[HoistKey]string{}
	used := map[string]bool{}

	for _, path := range files {
		pf := parseRefacFile(path, existing, used)

		if pf != nil {
			parsed = append(parsed, pf)
		}
	}

	// Phase 2: classify every hoist-eligible occurrence (free = in a function body),
	// in (file, source-position) order for deterministic name allocation.
	var occs []Occurrence

	for fi, pf := range parsed {
		collectOccurrences(pf, fi, &occs)
	}

	// emit gathers every const a dest file must declare: existing package-level
	// hoist vars (relocated as-is, preserving names) plus the new ones below.
	var emit []HoistedVar

	for _, pf := range parsed {
		emit = append(emit, pf.vars...)
	}

	// Phase 3: a canon gets a NEW var only if it lacks one and has a free
	// occurrence. A list-only canon stays inline (hoisting would make a single-use var).
	for _, o := range occs {
		if !o.free {
			continue
		}

		if _, ok := existing[o.key]; ok {
			continue
		}

		name := uniqueName(identForVFS(o.key), used)
		used[name] = true
		existing[o.key] = name
		emit = append(emit, HoistedVar{name, o.key})
	}

	// Phase 4: per non-dest file, rewrite occurrences whose canon now has a var and
	// delete existing hoist declarations (relocated to the dest file).
	editsByFile := make([][]ConstEdit, len(parsed))

	for _, o := range occs {
		name, ok := existing[o.key]

		if !ok {
			continue
		}

		editsByFile[o.fileIdx] = append(editsByFile[o.fileIdx], ConstEdit{o.start, o.end, name})
	}

	for fi, pf := range parsed {
		if dest[pf.path] {
			continue
		}

		editsByFile[fi] = append(editsByFile[fi], removalEdits(pf)...)
		editsByFile[fi] = append(editsByFile[fi], internArgsRewrites(pf, existing, used, &emit)...)

		if applyConstEdits(pf, editsByFile[fi]) {
			fmt.Fprintf(os.Stderr, "refac consts: rewrote %s\n", pf.path)
		}
	}

	// Phase 5: regenerate each per-kind dest file from its full set of hoisted vars.
	for kind, fname := range constFileForKind {
		generateConstFile(fname, kind, emit)
	}

	return 0
}

// occurrence is one hoist-eligible call site, located by byte offset in its file.
type Occurrence struct {
	fileIdx    int
	start, end int
	key        HoistKey
	free       bool // in a function body (justifies a var)
}

// collectOccurrences appends every hoist-eligible call in pf to occs, tagging each
// as free (inside a function body). Declared direct-value vars are skipped — they
// ARE the hoisted vars.
func collectOccurrences(pf *ParsedFile, fileIdx int, occs *[]Occurrence) {
	record := func(call *ast.CallExpr, free bool) bool {
		if pf.declared[call] {
			return false // a direct-value var declaration
		}

		key, ok := hoistCall(call)

		if !ok {
			return true
		}

		*occs = append(*occs, Occurrence{
			fileIdx: fileIdx,
			start:   pf.fset.Position(call.Pos()).Offset,
			end:     pf.fset.Position(call.End()).Offset,
			key:     key,
			free:    free,
		})

		return false // only child is the string literal
	}

	for _, decl := range pf.f.Decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			ast.Inspect(d, func(n ast.Node) bool {
				if call, ok := n.(*ast.CallExpr); ok {
					return record(call, true)
				}

				return true
			})
		case *ast.GenDecl:
			if d.Tok != gotoken.VAR && d.Tok != gotoken.CONST {
				continue
			}

			for _, spec := range d.Specs {
				vs, ok := spec.(*ast.ValueSpec)

				if !ok {
					continue
				}

				for _, val := range vs.Values {
					ast.Inspect(val, func(n ast.Node) bool {
						if call, ok := n.(*ast.CallExpr); ok {
							return record(call, false)
						}

						return true
					})
				}
			}
		}
	}
}

type ParsedFile struct {
	path     string
	src      []byte
	fset     *gotoken.FileSet
	f        *ast.File
	declared map[*ast.CallExpr]bool // hoist-eligible calls that already ARE var values
	vars     []HoistedVar           // every single-literal hoist declaration
}

// hoistedVar is a package-level const owned by a per-kind dest file.
type HoistedVar struct {
	name string
	key  HoistKey
}

// parseRefacFile parses path and folds its top-level declarations into the shared
// existing/used maps. Returns nil (warning) on parse failure.
func parseRefacFile(path string, existing map[HoistKey]string, used map[string]bool) *ParsedFile {
	src := throw2(os.ReadFile(path))
	fset := gotoken.NewFileSet()
	f, err := goparser.ParseFile(fset, path, src, goparser.ParseComments)

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac consts: %s: parse: %v\n", path, err)

		return nil
	}

	declared := map[*ast.CallExpr]bool{}
	var vars []HoistedVar

	for _, decl := range f.Decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			used[d.Name.Name] = true
		case *ast.GenDecl:
			for _, spec := range d.Specs {
				switch s := spec.(type) {
				case *ast.TypeSpec:
					used[s.Name.Name] = true
				case *ast.ValueSpec:
					for _, n := range s.Names {
						used[n.Name] = true
					}

					if d.Tok == gotoken.VAR || d.Tok == gotoken.CONST {
						for i, val := range s.Values {
							call, isCall := val.(*ast.CallExpr)

							if !isCall || i >= len(s.Names) {
								continue
							}

							if key, ok := hoistCall(call); ok {
								if _, seen := existing[key]; !seen {
									existing[key] = s.Names[i].Name
								}

								declared[call] = true
								vars = append(vars, HoistedVar{s.Names[i].Name, key})
							}
						}
					}
				}
			}
		}
	}

	return &ParsedFile{path: path, src: src, fset: fset, f: f, declared: declared, vars: vars}
}

// hoistKind is the result-type namespace of a hoistable literal call. Different
// kinds never share a var even when their canon matches.
type HoistKind uint8

const (
	hoistVFS HoistKind = iota // intern/source/build -> VFS
	hoistStr                  // internStr -> STR
	hoistArg                  // internArg -> ARG
	hoistEnv                  // internEnv -> ENV
)

// hoistKey is the dedup key. For hoistVFS, canon is the resolved VFS path, so
// source("x") and intern("$(S)/x") share one var; for hoistStr it is the raw literal.
type HoistKey struct {
	kind  HoistKind
	canon string
}

// hoistCall reports whether call is a single-literal intern-family call and
// returns its dedup key.
func hoistCall(call *ast.CallExpr) (HoistKey, bool) {
	id, isID := call.Fun.(*ast.Ident)

	if !isID {
		return HoistKey{}, false
	}

	if len(call.Args) != 1 {
		return HoistKey{}, false
	}

	bl, isLit := call.Args[0].(*ast.BasicLit)

	if !isLit || bl.Kind != gotoken.STRING {
		return HoistKey{}, false
	}

	lit, err := strconv.Unquote(bl.Value)

	if err != nil {
		return HoistKey{}, false
	}

	switch id.Name {
	case "intern":
		return HoistKey{kind: hoistVFS, canon: lit}, true
	case "source":
		return HoistKey{kind: hoistVFS, canon: "$(S)/" + lit}, true
	case "build":
		return HoistKey{kind: hoistVFS, canon: "$(B)/" + lit}, true
	case "internStr":
		return HoistKey{kind: hoistStr, canon: lit}, true
	case "internArg":
		return HoistKey{kind: hoistArg, canon: lit}, true
	case "internEnv":
		return HoistKey{kind: hoistEnv, canon: lit}, true
	}

	return HoistKey{}, false
}

// constDef renders the var initializer for a key, preferring source/build forms.
func constDef(key HoistKey) string {
	switch key.kind {
	case hoistStr:
		return fmt.Sprintf("internStr(%q)", key.canon)
	case hoistArg:
		return fmt.Sprintf("internArg(%q)", key.canon)
	case hoistEnv:
		return fmt.Sprintf("internEnv(%q)", key.canon)
	}

	if rel, ok := strings.CutPrefix(key.canon, "$(S)/"); ok {
		return fmt.Sprintf("source(%q)", rel)
	}

	if rel, ok := strings.CutPrefix(key.canon, "$(B)/"); ok {
		return fmt.Sprintf("build(%q)", rel)
	}

	return fmt.Sprintf("intern(%q)", key.canon)
}

// constEdit replaces the byte range [start,end) with name; an empty name deletes it.
type ConstEdit struct {
	start, end int
	name       string
}

// internArgsRewrites finds every all-literal `internArgs([]string{…})` call in pf,
// registers each element as a hoistArg const, and rewrites the call to a `[]ARG{…}`
// literal of pre-interned consts. A call with any non-literal element is untouched.
func internArgsRewrites(pf *ParsedFile, existing map[HoistKey]string, used map[string]bool, emit *[]HoistedVar) []ConstEdit {
	off := func(p gotoken.Pos) int { return pf.fset.Position(p).Offset }

	var edits []ConstEdit

	ast.Inspect(pf.f, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)

		if !ok {
			return true
		}

		id, isID := call.Fun.(*ast.Ident)

		if !isID || id.Name != "internArgs" || len(call.Args) != 1 {
			return true
		}

		cl, isComposite := call.Args[0].(*ast.CompositeLit)

		if !isComposite || len(cl.Elts) == 0 {
			return true
		}

		names := make([]string, 0, len(cl.Elts))

		for _, el := range cl.Elts {
			bl, isLit := el.(*ast.BasicLit)

			if !isLit || bl.Kind != gotoken.STRING {
				return true // non-literal element
			}

			lit, err := strconv.Unquote(bl.Value)

			if err != nil {
				return true
			}

			key := HoistKey{kind: hoistArg, canon: lit}
			name, seen := existing[key]

			if !seen {
				name = uniqueName(identForVFS(key), used)
				used[name] = true
				existing[key] = name
				*emit = append(*emit, HoistedVar{name, key})
			}

			names = append(names, name)
		}

		var b strings.Builder
		b.WriteString("[]ARG{")

		for _, nm := range names {
			b.WriteByte('\n')
			b.WriteString(nm)
			b.WriteByte(',')
		}

		b.WriteString("\n}")
		edits = append(edits, ConstEdit{off(call.Pos()), off(call.End()), b.String()})

		return false
	})

	return edits
}

// specRemovable reports whether spec is a hoistable `name = Call("<literal>")` var
// whose const is being relocated to a dest file.
func specRemovable(pf *ParsedFile, spec ast.Spec) bool {
	vs, ok := spec.(*ast.ValueSpec)

	if !ok || len(vs.Names) != 1 || len(vs.Values) != 1 {
		return false
	}

	call, ok := vs.Values[0].(*ast.CallExpr)

	return ok && pf.declared[call]
}

// removalEdits returns the byte ranges to delete so every relocated hoist
// declaration disappears. A var block whose specs all relocate drops whole (with
// its doc); otherwise each relocated spec drops on its own lines.
func removalEdits(pf *ParsedFile) []ConstEdit {
	src := pf.src
	off := func(p gotoken.Pos) int { return pf.fset.Position(p).Offset }

	lineStart := func(o int) int {
		for o > 0 && src[o-1] != '\n' {
			o--
		}

		return o
	}

	lineEndIncl := func(o int) int {
		for o < len(src) && src[o] != '\n' {
			o++
		}

		if o < len(src) {
			o++
		}

		return o
	}

	var edits []ConstEdit

	for _, decl := range pf.f.Decls {
		gd, ok := decl.(*ast.GenDecl)

		if !ok || gd.Tok != gotoken.VAR {
			continue
		}

		removable := 0

		for _, spec := range gd.Specs {
			if specRemovable(pf, spec) {
				removable++
			}
		}

		if removable == 0 {
			continue
		}

		if removable == len(gd.Specs) {
			start := gd.Pos()

			if gd.Doc != nil {
				start = gd.Doc.Pos()
			}

			edits = append(edits, ConstEdit{lineStart(off(start)), lineEndIncl(off(gd.End()) - 1), ""})

			continue
		}

		for _, spec := range gd.Specs {
			if !specRemovable(pf, spec) {
				continue
			}

			vs := spec.(*ast.ValueSpec)
			start := vs.Pos()

			if vs.Doc != nil {
				start = vs.Doc.Pos()
			}

			end := vs.End()

			if vs.Comment != nil {
				end = vs.Comment.End()
			}

			edits = append(edits, ConstEdit{lineStart(off(start)), lineEndIncl(off(end) - 1), ""})
		}
	}

	return edits
}

// applyConstEdits applies edits to pf back-to-front, formats, and writes. Returns
// whether the file changed.
func applyConstEdits(pf *ParsedFile, edits []ConstEdit) bool {
	if len(edits) == 0 {
		return false
	}

	sort.Slice(edits, func(i, j int) bool { return edits[i].start > edits[j].start })
	out := append([]byte(nil), pf.src...)

	for _, e := range edits {
		out = append(out[:e.start], append([]byte(e.name), out[e.end:]...)...)
	}

	formatted, err := format.Source(out)

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac consts: %s: format failed (left unchanged): %v\n", pf.path, err)

		return false
	}

	if bytes.Equal(formatted, pf.src) {
		return false
	}

	throw(os.WriteFile(pf.path, formatted, 0o644))

	return true
}

// generateConstFile (re)writes path with every hoisted var of kind, deduped and
// sorted by name. A file with no vars of its kind is removed if present.
func generateConstFile(path string, kind HoistKind, vars []HoistedVar) {
	var items []HoistedVar
	seen := map[string]bool{}

	for _, v := range vars {
		if v.key.kind != kind || seen[v.name] {
			continue
		}

		seen[v.name] = true
		items = append(items, v)
	}

	if len(items) == 0 {
		if _, err := os.Stat(path); err == nil {
			throw(os.Remove(path))
			fmt.Fprintf(os.Stderr, "refac consts: removed empty %s\n", path)
		}

		return
	}

	sort.Slice(items, func(i, j int) bool { return items[i].name < items[j].name })

	var b strings.Builder
	b.WriteString("package main\n\n")
	b.WriteString(constFileHeader[kind])
	b.WriteString("\nvar (\n")

	for _, it := range items {
		fmt.Fprintf(&b, "\t%s = %s\n", it.name, constDef(it.key))
	}

	b.WriteString(")\n")
	formatted := throw2(format.Source([]byte(b.String())))
	throw(os.WriteFile(path, formatted, 0o644))
	fmt.Fprintf(os.Stderr, "refac consts: generated %s (%d consts)\n", path, len(items))
}

// identForVFS turns a key into a lowerCamel identifier: the $(S)/$(B) prefix drops
// (with a leading "bld"/"str"/"arg"/"env" word to keep kinds distinct), and every
// non-alphanumeric run splits words.
func identForVFS(key HoistKey) string {
	s := key.canon
	var words []string

	switch {
	case key.kind == hoistStr:
		words = append(words, "str")
	case key.kind == hoistArg:
		words = append(words, "arg")
	case key.kind == hoistEnv:
		words = append(words, "env")
	default:
		if rel, ok := strings.CutPrefix(s, "$(S)/"); ok {
			s = rel
		} else if rel, ok := strings.CutPrefix(s, "$(B)/"); ok {
			s = rel
			words = append(words, "bld")
		}
	}

	var cur strings.Builder
	flush := func() {
		if cur.Len() > 0 {
			words = append(words, cur.String())
			cur.Reset()
		}
	}

	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			cur.WriteRune(r)
		} else {
			flush()
		}
	}

	flush()

	if len(words) == 0 {
		words = []string{"v"}
	}

	var b strings.Builder

	for i, w := range words {
		w = strings.ToLower(w)

		if i == 0 {
			b.WriteString(w)
		} else {
			b.WriteString(strings.ToUpper(w[:1]) + w[1:])
		}
	}

	id := b.String()

	if c := id[0]; c >= '0' && c <= '9' {
		id = "v" + id
	}

	return id
}

func uniqueName(base string, used map[string]bool) string {
	if !used[base] && !goKeyword[base] && !goPredeclared[base] {
		return base
	}

	for i := 2; ; i++ {
		cand := base + strconv.Itoa(i)

		if !used[cand] {
			return cand
		}
	}
}

// fileLinter rewrites one file in place and reports whether it changed it.
type FileLinter struct {
	name string
	run  func(path string) bool
}

// refacLint applies every linter, in order, to each file.
func refacLint(_ GlobalFlags, args []string) int {
	files := goFilesFromArgs(args)

	for _, path := range files {
		for _, l := range linters {
			if l.run(path) {
				fmt.Fprintf(os.Stderr, "refac lint: %s: %s\n", l.name, path)
			}
		}
	}

	return 0
}

// varItem is one package-level var spec extracted for consolidation. body holds the
// spec without `var`; doc/blockDoc are the spec's own and its block's doc comments;
// multiline marks a value spanning more than one line.
type VarItem struct {
	blockDoc  string
	doc       string
	body      string
	multiline bool
}

// render emits the item as a group entry (no `var`) or a standalone declaration.
func (it VarItem) render(inGroup bool) string {
	var b strings.Builder

	if it.blockDoc != "" {
		b.WriteString(it.blockDoc)
		b.WriteByte('\n')
	}

	if it.doc != "" {
		b.WriteString(it.doc)
		b.WriteByte('\n')
	}

	if !inGroup {
		b.WriteString("var ")
	}

	b.WriteString(it.body)

	return b.String()
}

// lintConsolidateVars groups a file's single-line package-level vars into one
// var(...) block after the imports; a multi-line var stays standalone below the
// group. Order and comments are preserved. Forms only with two+ single-line vars.
func lintConsolidateVars(path string) bool {
	src := throw2(os.ReadFile(path))
	fset := gotoken.NewFileSet()
	f, err := goparser.ParseFile(fset, path, src, goparser.ParseComments)

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac lint: %s: parse: %v\n", path, err)

		return false
	}

	var varDecls []*ast.GenDecl
	totalSpecs := 0

	for _, decl := range f.Decls {
		if gd, ok := decl.(*ast.GenDecl); ok && gd.Tok == gotoken.VAR {
			varDecls = append(varDecls, gd)
			totalSpecs += len(gd.Specs)
		}
	}

	if totalSpecs < 2 {
		return false
	}

	off := func(p gotoken.Pos) int { return fset.Position(p).Offset }
	text := func(lo, hi gotoken.Pos) string { return string(src[off(lo):off(hi)]) }
	type span struct{ start, end int }
	var items []VarItem
	var removals []span

	for _, gd := range varDecls {
		rmStart := off(gd.Pos())

		if gd.Doc != nil {
			rmStart = off(gd.Doc.Pos())
		}

		rmEnd := off(gd.End())

		// A grouped block's doc attaches once, to its first spec.
		blockDoc := ""

		if gd.Lparen.IsValid() && gd.Doc != nil {
			blockDoc = text(gd.Doc.Pos(), gd.Doc.End())
		}

		for _, spec := range gd.Specs {
			vs := spec.(*ast.ValueSpec)
			hi := vs.End()

			if vs.Comment != nil {
				hi = vs.Comment.End()

				if off(hi) > rmEnd {
					rmEnd = off(hi)
				}
			}

			doc := ""

			if vs.Doc != nil {
				doc = text(vs.Doc.Pos(), vs.Doc.End())
			} else if !gd.Lparen.IsValid() && gd.Doc != nil {
				doc = text(gd.Doc.Pos(), gd.Doc.End())
			}

			items = append(items, VarItem{
				blockDoc:  blockDoc,
				doc:       doc,
				body:      text(vs.Pos(), hi),
				multiline: strings.IndexByte(text(vs.Pos(), vs.End()), '\n') >= 0,
			})
			blockDoc = ""
		}

		removals = append(removals, span{rmStart, rmEnd})
	}

	simpleCount := 0

	for _, it := range items {
		if !it.multiline {
			simpleCount++
		}
	}

	group := simpleCount >= 2

	// Grouped block first, then standalone declarations for everything ungrouped.
	var parts []string

	if group {
		var b strings.Builder
		b.WriteString("var (\n")

		for _, it := range items {
			if it.multiline {
				continue
			}

			b.WriteString(it.render(true))
			b.WriteByte('\n')
		}

		b.WriteString(")")
		parts = append(parts, b.String())

		for _, it := range items {
			if it.multiline {
				parts = append(parts, it.render(false))
			}
		}
	} else {
		for _, it := range items {
			parts = append(parts, it.render(false))
		}
	}

	// Insert after the imports, or the package clause.
	insOff := off(f.Name.End())

	for _, decl := range f.Decls {
		if gd, ok := decl.(*ast.GenDecl); ok && gd.Tok == gotoken.IMPORT {
			insOff = off(gd.End())

			break
		}
	}

	// Delete originals back-to-front (each starts after insOff), then splice in the
	// rebuilt vars.
	out := append([]byte(nil), src...)
	sort.Slice(removals, func(i, j int) bool { return removals[i].start > removals[j].start })

	for _, r := range removals {
		out = append(out[:r.start], out[r.end:]...)
	}

	block := "\n\n" + strings.Join(parts, "\n\n") + "\n"
	out = append(out[:insOff], append([]byte(block), out[insOff:]...)...)

	formatted, err := format.Source(out)

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac lint: %s: consolidate-vars format failed (left unchanged): %v\n", path, err)

		return false
	}

	if bytes.Equal(formatted, src) {
		return false
	}

	throw(os.WriteFile(path, formatted, 0o644))

	return true
}

// isControlBlockStmt reports whether stmt requires blank lines around it:
// if/for/range/switch/select, go/defer of a func literal, and
// return/defer/continue/break. goto/fallthrough stay free. A labeled statement is
// judged by its inner stmt.
func isControlBlockStmt(stmt ast.Stmt) bool {
	switch s := stmt.(type) {
	case *ast.IfStmt, *ast.ForStmt, *ast.RangeStmt, *ast.SwitchStmt, *ast.TypeSwitchStmt, *ast.SelectStmt:
		return true
	case *ast.ReturnStmt, *ast.DeferStmt:
		return true
	case *ast.BranchStmt:
		return s.Tok == gotoken.BREAK || s.Tok == gotoken.CONTINUE
	case *ast.GoStmt:
		_, ok := s.Call.Fun.(*ast.FuncLit)

		return ok
	case *ast.LabeledStmt:
		return isControlBlockStmt(s.Stmt)
	}

	return false
}

// lintControlBlankLines enforces blank lines around every control block and flow
// statement, except where it is the first or last of its enclosing block. The
// invariant is pairwise: between two adjacent statements, if either is a control
// block there must be a blank. Inserts missing blanks only; gofmt collapses extras.
func lintControlBlankLines(path string) bool {
	src := throw2(os.ReadFile(path))
	fset := gotoken.NewFileSet()
	f, err := goparser.ParseFile(fset, path, src, goparser.ParseComments)

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac lint: %s: parse: %v\n", path, err)

		return false
	}

	lineOf := func(p gotoken.Pos) int { return fset.Position(p).Line }
	// Lines covered by a comment, so a control block's leading comment is skipped and
	// the blank goes above it.
	commentLine := map[int]bool{}

	for _, cg := range f.Comments {
		for _, c := range cg.List {
			for l := lineOf(c.Pos()); l <= lineOf(c.End()); l++ {
				commentLine[l] = true
			}
		}
	}

	insertBefore := map[int]bool{}
	process := func(list []ast.Stmt) {
		for i := 1; i < len(list); i++ {
			a, b := list[i-1], list[i]

			if !isControlBlockStmt(a) && !isControlBlockStmt(b) {
				continue
			}

			aEnd := lineOf(a.End())
			lead := lineOf(b.Pos())

			for l := lead - 1; l > aEnd && commentLine[l]; l-- {
				lead = l
			}

			if lead == aEnd+1 {
				insertBefore[lead] = true
			}
		}
	}

	ast.Inspect(f, func(n ast.Node) bool {
		switch node := n.(type) {
		case *ast.BlockStmt:
			process(node.List)
		case *ast.CaseClause:
			process(node.Body)
		case *ast.CommClause:
			process(node.Body)
		}

		return true
	})

	if len(insertBefore) == 0 {
		return false
	}

	lines := strings.Split(string(src), "\n")
	var b strings.Builder

	for i, ln := range lines {
		if insertBefore[i+1] {
			b.WriteByte('\n')
		}

		b.WriteString(ln)

		if i < len(lines)-1 {
			b.WriteByte('\n')
		}
	}

	formatted, err := format.Source([]byte(b.String()))

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac lint: %s: blank-around-blocks format failed (left unchanged): %v\n", path, err)

		return false
	}

	if bytes.Equal(formatted, src) {
		return false
	}

	throw(os.WriteFile(path, formatted, 0o644))

	return true
}

// lintTightBraces removes blank lines right after an opening brace and right before
// a closing one, for every brace pair. Positions come from the AST, so braces inside
// strings or comments never match. gofmt does not strip these blanks.
func lintTightBraces(path string) bool {
	src := throw2(os.ReadFile(path))
	fset := gotoken.NewFileSet()
	f, err := goparser.ParseFile(fset, path, src, goparser.ParseComments)

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac lint: %s: parse: %v\n", path, err)

		return false
	}

	lineOf := func(p gotoken.Pos) int { return fset.Position(p).Line }
	lines := strings.Split(string(src), "\n")
	isBlank := func(l int) bool { // l is 1-based
		return l >= 1 && l <= len(lines) && strings.TrimSpace(lines[l-1]) == ""
	}

	// del holds 1-based line numbers to drop. tighten removes blanks only strictly
	// between a brace pair's lines, so a same-line pair never touches outside blanks.
	del := map[int]bool{}
	tighten := func(open, close gotoken.Pos) {
		if !open.IsValid() || !close.IsValid() {
			return
		}

		openLine, closeLine := lineOf(open), lineOf(close)

		for l := openLine + 1; l < closeLine && isBlank(l); l++ {
			del[l] = true
		}

		for l := closeLine - 1; l > openLine && isBlank(l); l-- {
			del[l] = true
		}
	}

	ast.Inspect(f, func(n ast.Node) bool {
		switch x := n.(type) {
		case *ast.BlockStmt:
			tighten(x.Lbrace, x.Rbrace)
		case *ast.CompositeLit:
			tighten(x.Lbrace, x.Rbrace)
		case *ast.StructType:
			if x.Fields != nil {
				tighten(x.Fields.Opening, x.Fields.Closing)
			}
		case *ast.InterfaceType:
			if x.Methods != nil {
				tighten(x.Methods.Opening, x.Methods.Closing)
			}
		}

		return true
	})

	if len(del) == 0 {
		return false
	}

	kept := make([]string, 0, len(lines))

	for i, ln := range lines {
		if del[i+1] {
			continue
		}

		kept = append(kept, ln)
	}

	formatted, err := format.Source([]byte(strings.Join(kept, "\n")))

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac lint: %s: tight-braces format failed (left unchanged): %v\n", path, err)

		return false
	}

	if bytes.Equal(formatted, src) {
		return false
	}

	throw(os.WriteFile(path, formatted, 0o644))

	return true
}

// lintExpandFuncBodies rewrites single-line top-level function bodies into the
// multi-line form: gofmt preserves a one-line body but never expands it, so this
// inserts newlines after the opening and before the closing brace. Empty bodies
// are left alone.
func lintExpandFuncBodies(path string) bool {
	src := throw2(os.ReadFile(path))
	fset := gotoken.NewFileSet()
	f, err := goparser.ParseFile(fset, path, src, goparser.ParseComments)

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac lint: %s: parse: %v\n", path, err)

		return false
	}

	lineOf := func(p gotoken.Pos) int { return fset.Position(p).Line }
	offOf := func(p gotoken.Pos) int { return fset.Position(p).Offset }

	var offs []int // byte offsets to insert "\n" at

	for _, d := range f.Decls {
		fn, ok := d.(*ast.FuncDecl)

		if !ok || fn.Body == nil {
			continue
		}

		if lineOf(fn.Body.Lbrace) != lineOf(fn.Body.Rbrace) {
			continue
		}

		if len(fn.Body.List) == 0 {
			// empty body `{}` -> `{\n}`; one insertion suffices.
			offs = append(offs, offOf(fn.Body.Rbrace))

			continue
		}

		offs = append(offs, offOf(fn.Body.Lbrace)+1, offOf(fn.Body.Rbrace))
	}

	if len(offs) == 0 {
		return false
	}

	// Insert from the highest offset down so earlier offsets stay valid.
	sort.Sort(sort.Reverse(sort.IntSlice(offs)))
	b := src

	for _, off := range offs {
		b = append(b[:off:off], append([]byte("\n"), b[off:]...)...)
	}

	formatted, err := format.Source(b)

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac lint: %s: expand-func-bodies format failed (left unchanged): %v\n", path, err)

		return false
	}

	if bytes.Equal(formatted, src) {
		return false
	}

	throw(os.WriteFile(path, formatted, 0o644))

	return true
}

// lintFuncBlankLines ensures a blank line before and after every top-level function
// declaration. gofmt does not separate top-level decls itself, but collapses any
// duplicate blanks these create.
func lintFuncBlankLines(path string) bool {
	src := throw2(os.ReadFile(path))
	fset := gotoken.NewFileSet()
	f, err := goparser.ParseFile(fset, path, src, goparser.ParseComments)

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac lint: %s: parse: %v\n", path, err)

		return false
	}

	lineOf := func(p gotoken.Pos) int { return fset.Position(p).Line }
	lines := strings.Split(string(src), "\n")
	isBlank := func(l int) bool {
		return l >= 1 && l <= len(lines) && strings.TrimSpace(lines[l-1]) == ""
	}

	insertBefore := map[int]bool{}

	for _, d := range f.Decls {
		fn, ok := d.(*ast.FuncDecl)

		if !ok {
			continue
		}

		top := lineOf(fn.Pos())

		if fn.Doc != nil {
			top = lineOf(fn.Doc.Pos())
		}

		if top > 1 && !isBlank(top-1) {
			insertBefore[top] = true
		}

		end := lineOf(fn.End())

		if end+1 <= len(lines) && !isBlank(end+1) {
			insertBefore[end+1] = true
		}
	}

	if len(insertBefore) == 0 {
		return false
	}

	var b strings.Builder

	for i, ln := range lines {
		if insertBefore[i+1] {
			b.WriteByte('\n')
		}

		b.WriteString(ln)

		if i < len(lines)-1 {
			b.WriteByte('\n')
		}
	}

	formatted, err := format.Source([]byte(b.String()))

	if err != nil {
		fmt.Fprintf(os.Stderr, "refac lint: %s: func-blank-lines format failed (left unchanged): %v\n", path, err)

		return false
	}

	if bytes.Equal(formatted, src) {
		return false
	}

	throw(os.WriteFile(path, formatted, 0o644))

	return true
}
