package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	goparser "go/parser"
	gotoken "go/token"
	"os"
	"strings"
)

func refacReset(_ GlobalFlags, args []string) int {
	if len(args) == 0 {
		throwFmt("refac reset: expected struct type names")
	}

	want := map[string]bool{}

	for _, a := range args {
		want[a] = true
	}

	found := map[string]*ast.StructType{}
	fileOf := map[string]string{}

	for _, path := range goFilesFromArgs(nil) {
		src := throw2(os.ReadFile(path))
		fset := gotoken.NewFileSet()
		f := throw2(goparser.ParseFile(fset, path, src, 0))

		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)

			if !ok || gd.Tok != gotoken.TYPE {
				continue
			}

			for _, spec := range gd.Specs {
				ts := spec.(*ast.TypeSpec)

				if !want[ts.Name.Name] {
					continue
				}

				st, ok := ts.Type.(*ast.StructType)

				if !ok {
					throwFmt("refac reset: %s is not a struct", ts.Name.Name)
				}

				found[ts.Name.Name] = st
				fileOf[ts.Name.Name] = path
			}
		}
	}

	for _, name := range args {
		st := found[name]

		if st == nil {
			throwFmt("refac reset: type %s not found", name)
		}

		out := strings.TrimSuffix(fileOf[name], ".go") + "_reset_gen.go"

		var b bytes.Buffer

		fmt.Fprintf(&b, "// Code generated by `ay dev refac reset %s`. DO NOT EDIT.\n\npackage main\n\n", name)
		fmt.Fprintf(&b, "func (x *%s) reset() {\n", name)
		fmt.Fprintf(&b, "\t*x = %s{\n", name)

		for _, field := range st.Fields.List {
			for _, id := range field.Names {
				switch field.Type.(type) {
				case *ast.ArrayType:
					if field.Type.(*ast.ArrayType).Len == nil {
						fmt.Fprintf(&b, "\t\t%s: x.%s[:0],\n", id.Name, id.Name)
					}
				case *ast.MapType:
					fmt.Fprintf(&b, "\t\t%s: clearedMap(x.%s),\n", id.Name, id.Name)
				}
			}
		}

		fmt.Fprintf(&b, "\t}\n}\n")

		formatted := throw2(format.Source(b.Bytes()))

		if err := os.WriteFile(out, formatted, 0o644); err != nil {
			throwFmt("refac reset: %v", err)
		}

		fmt.Printf("refac reset: wrote %s\n", out)
	}

	return 0
}

func clearedMap[K comparable, V any](m map[K]V) map[K]V {
	clear(m)

	return m
}
