package main

var (
	// STR constants, interned once. Generated by `ay refac consts`.
	opensslUnistdTarget           = internStr("unistd.h")
	strAMXCFlags                  = internStr("-mamx-tile -mamx-int8 -mavx512f -mavx512cd -mavx512bw -mavx512dq -mavx512vl")
	strAVX2CFlags                 = internStr("-mavx2 -mfma -mbmi -mbmi2")
	strAVX512CFlags               = internStr("-mavx512f -mavx512cd -mavx512bw -mavx512dq -mavx512vl")
	strAVXCFlags                  = internStr("-mavx -mpclmul")
	strB                          = internStr("$(B)")
	strCPPProto                   = internStr("CPP_PROTO")
	strCX16CFlags                 = internStr("-mcx16")
	strNo                         = internStr("no")
	strPopcntCFlags               = internStr("-mpopcnt")
	strS                          = internStr("$(S)")
	strSSE41CFlags                = internStr("-msse4.1")
	strSSE42CFlags                = internStr("-msse4.2")
	strSSE4CFlags                 = internStr("-msse4.1 -msse4.2 -mpopcnt -mcx16")
	strSSECFlags                  = internStr("-msse2 -msse3 -mssse3")
	strTool                       = internStr("tool")
	strUtilGenericSerializedEnumH = internStr("util/generic/serialized_enum.h")
	strYes                        = internStr("yes")
)
