#!/usr/bin/env python3
"""gen_densemap.py — generate the multi-value DenseMap2..DenseMap5 types.

A DenseMapN maps a dense integer key K to N *independent* value columns, each
with its own presence and storage. The layout is one K-sized `idx` array that
maps a present key to a 1-based row slot in a compact `[]denseRowN`; each row
holds N 1-based slots (`i1..iN`), one per column, into that column's own dense
value table `valsM` (a row's `iM == 0` means column M is unset for that key).

Why not the alternatives:
  - N separate DenseMap[K, VM]: N K-sized idx arrays. The idx array (sized to
    the whole key universe, e.g. vfsBound) is the expensive part — DenseMapN
    shares ONE across all columns.
  - DenseMap[K, struct{V1..VN}]: one idx array, but every column shares a single
    slot, so a key that only ever sets V1 still stores a zero V2..VN, and "is VM
    present" needs a hand-rolled bool inside the struct. DenseMapN gives each
    column independent presence (iM sentinel) and independent dense storage.

Go generics cannot express a variadic number of type parameters, so the family
is code-generated. Run:  python3 dev/gen_densemap.py   (regenerates in place).
"""
import os
import subprocess
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Arities to generate. Only DenseMap3 is used in the tree (scanCache); 2/4/5 were
# generated but unused and removed. Add the arity here and re-run if one is needed.
ARITIES = [2, 3]


def type_params(n):
    return "K ~uint32, " + ", ".join(f"V{i}" for i in range(1, n + 1)) + " any"


def type_args(n):
    return "K, " + ", ".join(f"V{i}" for i in range(1, n + 1))


def recv(n):
    return f"(m *DenseMap{n}[{type_args(n)}])"


def gen(n):
    tp, ta, rv = type_params(n), type_args(n), recv(n)
    row_fields = ", ".join(f"i{i}" for i in range(1, n + 1)) + " uint32"
    out = []
    w = out.append

    w("// Code generated by dev/gen_densemap.py; DO NOT EDIT.\n")
    w("\npackage main\n")

    w(f"\n// denseRow{n} holds one 1-based slot per value column of a DenseMap{n}")
    w(" row;\n// a slot of 0 means that column is unset for the key.")
    w(f"\ntype denseRow{n} struct {{\n\t{row_fields}\n}}\n")

    w(f"\n// DenseMap{n} maps a dense integer key K to {n} independent value columns,")
    w("\n// each with its own presence and dense storage, sharing a single K-sized idx")
    w("\n// array. idx maps a present key to a 1-based row slot in rows; each row holds")
    w(f"\n// {n} 1-based slots, one per column, into that column's valsM table")
    w("\n// (a row slot of 0 = column unset for the key). See dev/gen_densemap.py for")
    w("\n// the rationale versus N separate DenseMaps or a DenseMap of a struct.")
    w(f"\ntype DenseMap{n}[{tp}] struct {{")
    w("\n\tidx  []uint32")
    w(f"\n\trows []denseRow{n}")
    for i in range(1, n + 1):
        w(f"\n\tvals{i} []V{i}")
    w("\n}\n")

    # rowSlot
    w(f"\n// rowSlot returns the 1-based row slot for k, or 0 when k has no row yet.")
    w(f"\nfunc {rv} rowSlot(k K) uint32 {{")
    w("\n\tif int(k) < len(m.idx) {\n\t\treturn m.idx[k]\n\t}\n")
    w("\n\treturn 0\n}\n")

    # ensureRow
    w("\n// ensureRow returns k's row slot, allocating an empty row on first touch.")
    w(f"\nfunc {rv} ensureRow(k K) uint32 {{")
    w("\n\tif int(k) < len(m.idx) {")
    w("\n\t\tif slot := m.idx[k]; slot != 0 {\n\t\t\treturn slot\n\t\t}\n\t}\n")
    w("\n\tif len(m.rows) == 0 {")
    w(f"\n\t\tm.rows = append(m.rows, denseRow{n}{{}}) // reserve slot 0 as the absent sentinel\n\t}}\n")
    w("\n\tm.growIdx(int(k))")
    w(f"\n\tm.rows = append(m.rows, denseRow{n}{{}})")
    w("\n\tslot := uint32(len(m.rows) - 1)")
    w("\n\tm.idx[k] = slot\n")
    w("\n\treturn slot\n}\n")

    # growIdx
    w(f"\nfunc {rv} growIdx(k int) {{")
    w("\n\tif k < len(m.idx) {\n\t\treturn\n\t}\n")
    w("\n\tn := len(m.idx) * 2\n")
    w("\n\tif n <= k {\n\t\tn = k + 1\n\t}\n")
    w("\n\tgrown := make([]uint32, n)")
    w("\n\tcopy(grown, m.idx)")
    w("\n\tm.idx = grown\n}\n")

    # Get/Put per column
    for i in range(1, n + 1):
        w(f"\n// Get{i} returns column {i}'s value for k and whether that column is present.")
        w(f"\nfunc {rv} Get{i}(k K) (V{i}, bool) {{")
        w("\n\tif slot := m.rowSlot(k); slot != 0 {")
        w(f"\n\t\tif vi := m.rows[slot].i{i}; vi != 0 {{")
        w(f"\n\t\t\treturn m.vals{i}[vi], true\n\t\t}}\n\t}}\n")
        w(f"\n\tvar zero V{i}\n")
        w("\n\treturn zero, false\n}\n")

        w(f"\n// Put{i} sets column {i}'s value for k.")
        w(f"\nfunc {rv} Put{i}(k K, v V{i}) {{")
        w("\n\tslot := m.ensureRow(k)\n")
        w(f"\n\tif vi := m.rows[slot].i{i}; vi != 0 {{")
        w(f"\n\t\tm.vals{i}[vi] = v\n")
        w("\n\t\treturn\n\t}\n")
        w(f"\n\tif len(m.vals{i}) == 0 {{")
        w(f"\n\t\tm.vals{i} = append(m.vals{i}, *new(V{i})) // reserve slot 0 as the absent sentinel\n\t}}\n")
        w(f"\n\tm.vals{i} = append(m.vals{i}, v)")
        w(f"\n\tm.rows[slot].i{i} = uint32(len(m.vals{i}) - 1)\n}}\n")

    # Len
    w("\n// Len reports the number of distinct keys stored (a key counts once any of")
    w("\n// its columns has been set).")
    w(f"\nfunc {rv} Len() int {{")
    w("\n\tif len(m.rows) == 0 {\n\t\treturn 0\n\t}\n")
    w("\n\treturn len(m.rows) - 1\n}\n")

    return "".join(out)


def gen_test(n):
    inst = f"DenseMap{n}[STR, " + ", ".join("int" for _ in range(n)) + "]"
    out = []
    w = out.append

    w("// Code generated by dev/gen_densemap.py; DO NOT EDIT.\n")
    w("\npackage main\n")
    w('\nimport "testing"\n')

    # Each key sets exactly one column; every other column must read absent.
    w(f"\nfunc TestDenseMap{n}_IndependentColumns(t *testing.T) {{")
    w(f"\n\tvar m {inst}\n")
    w("\n\t// Set exactly one column per key (key 0 exercises the slot-0 sentinel).")
    for c in range(1, n + 1):
        w(f"\n\tm.Put{c}({c - 1}, {c * 100})")
    w("\n")
    w(f"\n\tif m.Len() != {n} {{")
    w(f'\n\t\tt.Fatalf("Len = %d, want {n}", m.Len())\n\t}}\n')
    w("\n\t// Each key has only its own column present; all others read absent.")
    for c in range(1, n + 1):
        key = c - 1
        w(f"\n\tif got, ok := m.Get{c}({key}); !ok || got != {c * 100} {{")
        w(f'\n\t\tt.Fatalf("Get{c}({key}) = (%d, %v), want ({c * 100}, true)", got, ok)\n\t}}')
        for d in range(1, n + 1):
            if d == c:
                continue
            w(f"\n\tif _, ok := m.Get{d}({key}); ok {{")
            w(f'\n\t\tt.Fatalf("Get{d}({key}) present, want absent")\n\t}}')
    w("\n}\n")

    # One key carrying every column at once.
    w(f"\nfunc TestDenseMap{n}_AllColumnsOneKey(t *testing.T) {{")
    w(f"\n\tvar m {inst}")
    w("\n\tconst k = 1000\n")
    for c in range(1, n + 1):
        w(f"\n\tm.Put{c}(k, {c})")
    w("\n")
    for c in range(1, n + 1):
        w(f"\n\tif got, ok := m.Get{c}(k); !ok || got != {c} {{")
        w(f'\n\t\tt.Fatalf("Get{c}(k) = (%d, %v), want ({c}, true)", got, ok)\n\t}}')
    w("\n")
    w('\n\tif m.Len() != 1 {\n\t\tt.Fatalf("Len = %d, want 1", m.Len())\n\t}\n}\n')

    # Overwrite (column 1), empty + out-of-range lookups.
    w(f"\nfunc TestDenseMap{n}_OverwriteAndAbsent(t *testing.T) {{")
    w(f"\n\tvar m {inst}\n")
    w('\n\tif _, ok := m.Get1(0); ok {\n\t\tt.Fatal("empty map reported key 0 present")\n\t}')
    w('\n\tif _, ok := m.Get1(1 << 20); ok {\n\t\tt.Fatal("empty map reported out-of-range key present")\n\t}\n')
    w("\n\tm.Put1(7, 1)\n\tm.Put1(7, 2)\n\tm.Put1(7, 3)\n")
    w('\n\tif got, _ := m.Get1(7); got != 3 {\n\t\tt.Fatalf("Get1(7) = %d, want 3 (last write)", got)\n\t}')
    w('\n\tif m.Len() != 1 {\n\t\tt.Fatalf("Len = %d, want 1 (overwrite must not add a key)", m.Len())\n\t}\n}\n')

    return "".join(out)


def main():
    written = []

    for n in ARITIES:
        for path, body in (
            (os.path.join(REPO_ROOT, f"dense_map_{n}.go"), gen(n)),
            (os.path.join(REPO_ROOT, f"dense_map_{n}_test.go"), gen_test(n)),
        ):
            with open(path, "w") as f:
                f.write(body)

            written.append(path)

    # Canonicalize formatting (tabs/alignment) so output matches `go build` vet.
    subprocess.run(["gofmt", "-w", *written], check=True)

    for p in written:
        print("wrote", os.path.relpath(p, REPO_ROOT))


if __name__ == "__main__":
    sys.exit(main())
