#!/usr/bin/env python3
"""Generate the optimized DenseMap2 implementation.

A DenseMapN maps a dense integer key K to N *independent* value columns, each
with its own presence and storage. The layout is one K-sized `idx` array that
maps a present key to a 1-based slot; the slot indexes a `set` bitmask, whose
bit M-1 says whether column M is present for that key, and each column's own
value table `valsM`.

Why not the alternatives:
  - N separate DenseMap[K, VM]: N K-sized idx arrays. The idx array (sized to
    the whole key universe, e.g. vfsBound) is the expensive part — DenseMapN
    shares ONE across all columns.
  - DenseMap[K, struct{V1..VN}]: one idx array, but every column shares a single
    slot, so a key that only ever sets V1 still stores a zero V2..VN, and "is VM
    present" needs a hand-rolled bool inside the struct. DenseMapN gives each
    column independent presence (iM sentinel) and independent dense storage.

Go generics cannot express a variadic number of type parameters, so the family
is generated into the build tree.
"""
import argparse
from pathlib import Path

ARITIES = [2]


def type_params(n):
    return "K ~uint32, " + ", ".join(f"V{i}" for i in range(1, n + 1)) + " any"


def type_args(n):
    return "K, " + ", ".join(f"V{i}" for i in range(1, n + 1))


def recv(n):
    return f"(m *DenseMap{n}[{type_args(n)}])"


def gen_packed(n):
    if n > 8:
        raise ValueError("packed DenseMap supports at most 8 columns")

    tp, ta, rv = type_params(n), type_args(n), recv(n)
    out = []
    w = out.append

    w("// Code generated by dev/gen_densemap.py; DO NOT EDIT.\n")
    w("\npackage main\n")
    w(f"\ntype DenseMap{n}[{tp}] struct {{")
    w("\n\tidx   Vec[uint32]")
    w("\n\tset   Vec[uint8]")
    for i in range(1, n + 1):
        w(f"\n\tvals{i} Vec[V{i}]")
    w("\n}\n")

    w(f"\nfunc {rv} rowSlot(k K) uint32 {{")
    w("\n\tif int(k) < len(m.idx.s) {\n\t\treturn m.idx.s[k]\n\t}\n")
    w("\n\treturn 0\n}\n")

    w(f"\nfunc {rv} ensureRow(k K) uint32 {{")
    w("\n\tif int(k) < len(m.idx.s) {")
    w("\n\t\tif slot := m.idx.s[k]; slot != 0 {\n\t\t\treturn slot\n\t\t}\n\t}\n")
    w("\n\tif len(m.set.s) == 0 {")
    w("\n\t\tm.set.pushBack(0)")
    for i in range(1, n + 1):
        w(f"\n\t\tm.vals{i}.pushBack(*new(V{i}))")
    w("\n\t}\n")
    w("\n\tm.idx.ensureLen(int(k) + 1)")
    w("\n\tm.set.pushBack(0)")
    for i in range(1, n + 1):
        w(f"\n\tm.vals{i}.pushBack(*new(V{i}))")
    w("\n\n\tslot := uint32(len(m.set.s) - 1)\n")
    w("\n\tm.idx.s[k] = slot\n")
    w("\n\treturn slot\n}\n")

    for i in range(1, n + 1):
        bit = 1 << (i - 1)
        w(f"\nfunc {rv} get{i}(k K) (V{i}, bool) {{")
        w("\n\tif slot := m.rowSlot(k); slot != 0 {")
        w(f"\n\t\tif *unsafeAt(m.set.s, uint64(slot))&{bit} != 0 {{")
        w(f"\n\t\t\treturn *unsafeAt(m.vals{i}.s, uint64(slot)), true\n\t\t}}\n\t}}\n")
        w(f"\n\tvar zero V{i}\n")
        w("\n\treturn zero, false\n}\n")

        w(f"\nfunc {rv} put{i}(k K, v V{i}) {{")
        w("\n\tslot := m.ensureRow(k)\n")
        w(f"\n\t*unsafeAt(m.vals{i}.s, uint64(slot)) = v")
        w(f"\n\t*unsafeAt(m.set.s, uint64(slot)) |= {bit}\n}}\n")

    w(f"\nfunc {rv} len() int {{")
    w("\n\tif len(m.set.s) == 0 {\n\t\treturn 0\n\t}\n")
    w("\n\treturn len(m.set.s) - 1\n}\n")

    return "".join(out)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out-dir", required=True)
    args = parser.parse_args()
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []

    for n in ARITIES:
        path = out_dir / f"dense_map_{n}.go"

        path.write_text(gen_packed(n), encoding="utf-8")
        written.append(str(path))

    for p in written:
        print("wrote", p)


if __name__ == "__main__":
    main()
