#!/usr/bin/env python3
"""Generate the optimized DenseMap2 and DenseMap3 implementations.

A DenseMapN maps a dense integer key K to N *independent* value columns, each
with its own presence and storage. The layout is one K-sized `idx` array that
maps a present key to a 1-based row slot in a compact `[]denseRowN`; each row
holds N 1-based slots (`i1..iN`), one per column, into that column's own dense
value table `valsM` (a row's `iM == 0` means column M is unset for that key).

Why not the alternatives:
  - N separate DenseMap[K, VM]: N K-sized idx arrays. The idx array (sized to
    the whole key universe, e.g. vfsBound) is the expensive part — DenseMapN
    shares ONE across all columns.
  - DenseMap[K, struct{V1..VN}]: one idx array, but every column shares a single
    slot, so a key that only ever sets V1 still stores a zero V2..VN, and "is VM
    present" needs a hand-rolled bool inside the struct. DenseMapN gives each
    column independent presence (iM sentinel) and independent dense storage.

Go generics cannot express a variadic number of type parameters, so the family
is generated into the build tree.
"""
import argparse
from pathlib import Path

ARITIES = [2, 3]


def type_params(n):
    return "K ~uint32, " + ", ".join(f"V{i}" for i in range(1, n + 1)) + " any"


def type_args(n):
    return "K, " + ", ".join(f"V{i}" for i in range(1, n + 1))


def recv(n):
    return f"(m *DenseMap{n}[{type_args(n)}])"


def gen_packed(n):
    if n > 8:
        raise ValueError("packed DenseMap supports at most 8 columns")

    tp, ta, rv = type_params(n), type_args(n), recv(n)
    out = []
    w = out.append

    w("// Code generated by dev/gen_densemap.py; DO NOT EDIT.\n")
    w("\npackage main\n")
    w(f"\ntype DenseMap{n}[{tp}] struct {{")
    w("\n\tidx   Vec[uint32]")
    w("\n\tset   Vec[uint8]")
    for i in range(1, n + 1):
        w(f"\n\tvals{i} Vec[V{i}]")
    w("\n}\n")

    w(f"\nfunc {rv} rowSlot(k K) uint32 {{")
    w("\n\tif int(k) < len(m.idx.s) {\n\t\treturn m.idx.s[k]\n\t}\n")
    w("\n\treturn 0\n}\n")

    w(f"\nfunc {rv} ensureRow(k K) uint32 {{")
    w("\n\tif int(k) < len(m.idx.s) {")
    w("\n\t\tif slot := m.idx.s[k]; slot != 0 {\n\t\t\treturn slot\n\t\t}\n\t}\n")
    w("\n\tif len(m.set.s) == 0 {")
    w("\n\t\tm.set.pushBack(0)")
    for i in range(1, n + 1):
        w(f"\n\t\tm.vals{i}.pushBack(*new(V{i}))")
    w("\n\t}\n")
    w("\n\tm.idx.ensureLen(int(k) + 1)")
    w("\n\tm.set.pushBack(0)")
    for i in range(1, n + 1):
        w(f"\n\tm.vals{i}.pushBack(*new(V{i}))")
    w("\n\n\tslot := uint32(len(m.set.s) - 1)\n")
    w("\n\tm.idx.s[k] = slot\n")
    w("\n\treturn slot\n}\n")

    for i in range(1, n + 1):
        bit = 1 << (i - 1)
        w(f"\nfunc {rv} get{i}(k K) (V{i}, bool) {{")
        w("\n\tif slot := m.rowSlot(k); slot != 0 {")
        w(f"\n\t\tif *unsafeAt(m.set.s, uint64(slot))&{bit} != 0 {{")
        w(f"\n\t\t\treturn *unsafeAt(m.vals{i}.s, uint64(slot)), true\n\t\t}}\n\t}}\n")
        w(f"\n\tvar zero V{i}\n")
        w("\n\treturn zero, false\n}\n")

        w(f"\nfunc {rv} put{i}(k K, v V{i}) {{")
        w("\n\tslot := m.ensureRow(k)\n")
        w(f"\n\t*unsafeAt(m.vals{i}.s, uint64(slot)) = v")
        w(f"\n\t*unsafeAt(m.set.s, uint64(slot)) |= {bit}\n}}\n")

    w(f"\nfunc {rv} len() int {{")
    w("\n\tif len(m.set.s) == 0 {\n\t\treturn 0\n\t}\n")
    w("\n\treturn len(m.set.s) - 1\n}\n")

    return "".join(out)


def gen_rows(n):
    tp, ta, rv = type_params(n), type_args(n), recv(n)
    row_fields = ", ".join(f"i{i}" for i in range(1, n + 1)) + " uint32"
    out = []
    w = out.append

    w("// Code generated by dev/gen_densemap.py; DO NOT EDIT.\n")
    w("\npackage main\n")

    w(f"\ntype DenseRow{n} struct {{\n\t{row_fields}\n}}\n")
    w(f"\ntype DenseMap{n}[{tp}] struct {{")
    w("\n\tidx   Vec[uint32]")
    w(f"\n\trows  Vec[DenseRow{n}]")
    for i in range(1, n + 1):
        w(f"\n\tvals{i} Vec[V{i}]")
    w("\n}\n")

    w(f"\nfunc {rv} rowSlot(k K) uint32 {{")
    w("\n\tif int(k) < m.idx.len() {\n\t\treturn m.idx.s[k]\n\t}\n")
    w("\n\treturn 0\n}\n")

    w(f"\nfunc {rv} ensureRow(k K) uint32 {{")
    w("\n\tif int(k) < m.idx.len() {")
    w("\n\t\tif slot := m.idx.s[k]; slot != 0 {\n\t\t\treturn slot\n\t\t}\n\t}\n")
    w("\n\tif m.rows.len() == 0 {")
    w(f"\n\t\tm.rows.pushBack(DenseRow{n}{{}})\n\t}}\n")
    w("\n\tm.idx.ensureLen(int(k) + 1)")
    w(f"\n\tm.rows.pushBack(DenseRow{n}{{}})\n")
    w("\n\tslot := uint32(m.rows.len() - 1)")
    w("\n\n\tm.idx.s[k] = slot\n")
    w("\n\treturn slot\n}\n")

    for i in range(1, n + 1):
        w(f"\nfunc {rv} get{i}(k K) (V{i}, bool) {{")
        w("\n\tif slot := m.rowSlot(k); slot != 0 {")
        w(f"\n\t\tif vi := m.rows.s[slot].i{i}; vi != 0 {{")
        w(f"\n\t\t\treturn m.vals{i}.s[vi], true\n\t\t}}\n\t}}\n")
        w(f"\n\tvar zero V{i}\n")
        w("\n\treturn zero, false\n}\n")

        w(f"\nfunc {rv} put{i}(k K, v V{i}) {{")
        w("\n\tslot := m.ensureRow(k)\n")
        w(f"\n\tif vi := m.rows.s[slot].i{i}; vi != 0 {{")
        w(f"\n\t\tm.vals{i}.s[vi] = v\n")
        w("\n\t\treturn\n\t}\n")
        w(f"\n\tif m.vals{i}.len() == 0 {{")
        w(f"\n\t\tm.vals{i}.pushBack(*new(V{i}))\n\t}}\n")
        w(f"\n\tm.vals{i}.pushBack(v)")
        w(f"\n\tm.rows.s[slot].i{i} = uint32(m.vals{i}.len() - 1)\n}}\n")

    w(f"\nfunc {rv} len() int {{")
    w("\n\tif m.rows.len() == 0 {\n\t\treturn 0\n\t}\n")
    w("\n\treturn m.rows.len() - 1\n}\n")

    return "".join(out)


def gen(n):
    if n == 2:
        return gen_packed(n)

    return gen_rows(n)


def gen_test(n):
    inst = f"DenseMap{n}[STR, " + ", ".join("int" for _ in range(n)) + "]"
    out = []
    w = out.append

    w("// Code generated by dev/gen_densemap.py; DO NOT EDIT.\n")
    w("\npackage main\n")
    w('\nimport "testing"\n')

    # Each key sets exactly one column; every other column must read absent.
    w(f"\nfunc TestDenseMap{n}_IndependentColumns(t *testing.T) {{")
    w(f"\n\tvar m {inst}\n")
    w("\n\t// Set exactly one column per key (key 0 exercises the slot-0 sentinel).")
    for c in range(1, n + 1):
        w(f"\n\tm.put{c}({c - 1}, {c * 100})")
    w("\n")
    w(f"\n\tif m.len() != {n} {{")
    w(f'\n\t\tt.Fatalf("len = %d, want {n}", m.len())\n\t}}\n')
    w("\n\t// Each key has only its own column present; all others read absent.")
    for c in range(1, n + 1):
        key = c - 1
        w(f"\n\tif got, ok := m.get{c}({key}); !ok || got != {c * 100} {{")
        w(f'\n\t\tt.Fatalf("get{c}({key}) = (%d, %v), want ({c * 100}, true)", got, ok)\n\t}}')
        for d in range(1, n + 1):
            if d == c:
                continue
            w(f"\n\tif _, ok := m.get{d}({key}); ok {{")
            w(f'\n\t\tt.Fatalf("get{d}({key}) present, want absent")\n\t}}')
    w("\n}\n")

    # One key carrying every column at once.
    w(f"\nfunc TestDenseMap{n}_AllColumnsOneKey(t *testing.T) {{")
    w(f"\n\tvar m {inst}")
    w("\n\tconst k = 1000\n")
    for c in range(1, n + 1):
        w(f"\n\tm.put{c}(k, {c})")
    w("\n")
    for c in range(1, n + 1):
        w(f"\n\tif got, ok := m.get{c}(k); !ok || got != {c} {{")
        w(f'\n\t\tt.Fatalf("get{c}(k) = (%d, %v), want ({c}, true)", got, ok)\n\t}}')
    w("\n")
    w('\n\tif m.len() != 1 {\n\t\tt.Fatalf("len = %d, want 1", m.len())\n\t}\n}\n')

    # Overwrite (column 1), empty + out-of-range lookups.
    w(f"\nfunc TestDenseMap{n}_OverwriteAndAbsent(t *testing.T) {{")
    w(f"\n\tvar m {inst}\n")
    w('\n\tif _, ok := m.get1(0); ok {\n\t\tt.Fatal("empty map reported key 0 present")\n\t}')
    w('\n\tif _, ok := m.get1(1 << 20); ok {\n\t\tt.Fatal("empty map reported out-of-range key present")\n\t}\n')
    w("\n\tm.put1(7, 1)\n\tm.put1(7, 2)\n\tm.put1(7, 3)\n")
    w('\n\tif got, _ := m.get1(7); got != 3 {\n\t\tt.Fatalf("get1(7) = %d, want 3 (last write)", got)\n\t}')
    w('\n\tif m.len() != 1 {\n\t\tt.Fatalf("len = %d, want 1 (overwrite must not add a key)", m.len())\n\t}\n}\n')

    return "".join(out)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out-dir", required=True)
    args = parser.parse_args()
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []

    for n in ARITIES:
        for path, body in (
            (out_dir / f"dense_map_{n}.go", gen(n)),
            (out_dir / f"dense_map_{n}_test.go", gen_test(n)),
        ):
            path.write_text(body, encoding="utf-8")

            written.append(str(path))

    for p in written:
        print("wrote", p)


if __name__ == "__main__":
    main()
