#!/usr/bin/env python3
"""Generates parsers_generated.go: the extension -> include-directive-parser
dispatch. This script OWNS the extension registrations; to add or move an
extension, edit PARSERS below and re-run. The emitted lookup is a per-length
perfect hash (a linear combination of 1-3 extension bytes mod the length
group's table size), searched here at generation time, with a final string
compare rejecting unregistered extensions."""
import itertools
import pathlib

# The registration data: parser type -> registered extensions.
PARSERS = {
    'CIncludeDirectiveParser': [
        '.cpp', '.cc', '.cxx', '.c', '.C', '.auxcpp',
        '.h', '.hh', '.hpp', '.cuh', '.H', '.hxx', '.xh', '.ipp', '.ixx', '.inl',
        '.vert', '.frag', '.tesc', '.tese', '.geom', '.comp',
        '.cu', '.S', '.s', '.sfdl', '.m', '.mm',
        '.l', '.lex', '.lpp', '.y', '.ypp', '.gperf', '.asp',
        '.go',
    ],
    'RagelIncludeDirectiveParser': ['.rl', '.rh', '.rli', '.rl6', '.rl5'],
    'CythonIncludeDirectiveParser': ['.pyx', '.pxd', '.pxi', '.pyx.pxi', '.pxd.pxi'],
    'FlatbuffersIncludeDirectiveParser': ['.fbs', '.fbs64'],
    'ProtoIncludeDirectiveParser': ['.proto', '.ev', '.gzt', '.gztproto'],
    'SwigIncludeDirectiveParser': ['.swg'],
    'YasmIncludeDirectiveParser': ['.asm', '.asi'],
    'EmptyIncludeDirectiveParser': ['.g4', '.stg', '.m4'],
}

COEFS = (1, 2, 3, 4, 5, 7, 8, 9, 11, 13, 16, 19, 23, 31, 37, 64)


def search(grp, length):
    n = len(grp)
    for npos in (1, 2, 3):
        for poss in itertools.combinations(range(1, length), npos):
            for coefs in itertools.product(COEFS, repeat=npos):
                for mod in range(n, n + 48):
                    hs = set(sum(c * ord(e[p]) for c, p in zip(coefs, poss)) % mod for e in grp)
                    if len(hs) == n:
                        return mod, poss, coefs
    raise SystemExit(f'len {length}: no perfect hash in the search space; widen COEFS/mod range. exts={grp}')


def main():
    ext_parser = {}
    for parser, exts in PARSERS.items():
        for e in exts:
            assert e not in ext_parser, f'{e} registered twice'
            ext_parser[e] = parser

    bylen = {}
    for e in ext_parser:
        bylen.setdefault(len(e), []).append(e)

    slots = {}
    cases = []
    base = 0
    for length in sorted(bylen):
        grp = sorted(bylen[length])
        mod, poss, coefs = search(grp, length)
        for e in grp:
            h = sum(c * ord(e[p]) for c, p in zip(coefs, poss)) % mod
            slots[base + h] = e
        terms = '+'.join(
            (f'uint32(ext[{p}])' if c == 1 else f'{c}*uint32(ext[{p}])')
            for c, p in zip(coefs, poss))
        expr = terms if len(poss) > 1 or coefs[0] != 1 else terms
        if mod == 1:
            idx = str(base)
        else:
            idx = f'{base} + ({expr})%{mod}' if base else f'({expr})%{mod}'
        cases.append((length, idx))
        base += mod

    out = ['// Code generated by dev/gen_parsers.py. DO NOT EDIT.',
           '//',
           '// The extension -> include-directive-parser dispatch: a per-length perfect',
           '// hash over the registered extension set (the registrations live in the',
           '// generator). One arithmetic hash, one slot read, one string compare.',
           'package main', '',
           'type extSlot struct {',
           '\text    string',
           '\tparser IncludeDirectiveParser',
           '}', '',
           f'var extSlots = [{base}]extSlot{{']
    for i in sorted(slots):
        e = slots[i]
        out.append(f'\t{i}: {{{e!r}, {ext_parser[e]}{{}}}},'.replace("'", '"'))
    out += ['}', '',
            '// lookupParserByExt returns the registered parser for an extension, or nil.',
            'func lookupParserByExt(ext string) IncludeDirectiveParser {',
            '\tvar i uint32', '',
            '\tswitch len(ext) {']
    for length, idx in cases:
        out += [f'\tcase {length}:', f'\t\ti = {idx}']
    out += ['\tdefault:', '\t\treturn nil', '\t}', '',
            '\tif extSlots[i].ext != ext {', '\t\treturn nil', '\t}', '',
            '\treturn extSlots[i].parser', '}', '']
    target = pathlib.Path(__file__).parent.parent / 'parsers_generated.go'
    target.write_text('\n'.join(out))
    print(f'wrote {target}: {base} slots, {len(ext_parser)} extensions')


main()
